package net.oceancanvas.core.expansion;

import net.oceancanvas.core.config.CoreConfig;

import java.io.IOException;
import java.nio.channels.FileChannel;
import java.nio.channels.FileLock;
import java.nio.channels.OverlappingFileLockException;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;

/**
 * Independent immutable two-chunk plan authority. Both chunks and all world
 * geometry must match the first published plan on every server restart.
 * A new config cannot silently redirect the unstarted second chunk.
 */
public final class TwoChunkCanaryIdentityStore {
    private TwoChunkCanaryIdentityStore() {}

    public static void ensureExact(Path file, TwoChunkCanaryPlan plan, CoreConfig core) throws IOException {
        byte[] expected = canonicalBytes(plan, core);
        Files.createDirectories(file.toAbsolutePath().getParent());
        Path leasePath = file.resolveSibling(file.getFileName().toString() + ".lock");
        try (FileChannel lockChannel = FileChannel.open(leasePath,
                StandardOpenOption.CREATE, StandardOpenOption.WRITE);
             FileLock lease = lockChannel.tryLock()) {
            if (lease == null) throw new IOException("another two-chunk plan publisher is active");
            // A canonical plan plus an orphan staged plan should never be
            // generated by a completed atomic publication. Do not silently
            // choose one authority when interrupted/conflicting evidence exists.
            Path stage = file.resolveSibling(file.getFileName().toString() + ".tmp");
            if (Files.exists(file) && Files.exists(stage)) {
                throw new IOException("ambiguous canonical and staged two-chunk plans; preserve evidence");
            }
            if (Files.exists(file)) {
                if (Files.size(file) != expected.length
                        || !MessageDigest.isEqual(expected, Files.readAllBytes(file))) {
                    throw new IOException("immutable two-chunk plan changed; refuse additional authoring");
                }
                return;
            }
            // Do not erase staging bytes from a crashed attempted publication.
            Files.write(stage, expected, StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE);
            try (FileChannel channel = FileChannel.open(stage, StandardOpenOption.WRITE)) {
                channel.force(true);
            }
            try {
                Files.move(stage, file, StandardCopyOption.ATOMIC_MOVE);
            } catch (AtomicMoveNotSupportedException e) {
                throw new IOException("atomic two-chunk plan publication unavailable; stage retained", e);
            }
        } catch (OverlappingFileLockException e) {
            throw new IOException("another two-chunk plan publisher is active", e);
        }
    }

    private static byte[] canonicalBytes(TwoChunkCanaryPlan plan, CoreConfig core) throws IOException {
        String identity = "OCEANCANVAS_TWO_CHUNK_PLAN_V1\n"
                + "firstX=" + plan.first().x() + "\nfirstZ=" + plan.first().z()
                + "\nsecondX=" + plan.second().x() + "\nsecondZ=" + plan.second().z()
                + "\ncanvasSize=" + core.canvasSize()
                + "\ncenterX=" + core.centerX() + "\ncenterZ=" + core.centerZ()
                + "\nwaterSurfaceY=" + core.waterSurfaceY()
                + "\noceanFloorY=" + core.oceanFloorY()
                + "\noceanFloorVariation=" + core.oceanFloorVariation() + "\n";
        try {
            String digest = HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256")
                    .digest(identity.getBytes(StandardCharsets.UTF_8)));
            return (identity + "sha256=" + digest + "\n").getBytes(StandardCharsets.UTF_8);
        } catch (NoSuchAlgorithmException e) {
            throw new IOException("SHA-256 unavailable for durable two-chunk identity", e);
        }
    }
}
