package net.oceancanvas.core.receipt;

public enum ReceiptKind {
    TICKET_INSTALLED,
    CHUNK_RESIDENT,
    PHYSICAL_AUTHORING_COMPLETE,
    PHYSICAL_SETTLEMENT_RECONCILED,
    PHYSICAL_SETTLEMENT_VERIFIED,
    SAVE_FLUSH_COMPLETE,
    LIGHT_REQUEST_COMPLETE,
    SERVER_VERIFICATION_COMPLETE,
    TICKET_RELEASED,
    FAILURE_CLEANUP_RELEASED,
    ACCEPTANCE_HOLD,
    ACCEPTANCE_RESTART_VERIFIED,
    ACCEPTANCE_FINAL_RESTART_VERIFIED
}
