package net.oceancanvas.mod.project;

import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.resources.Identifier;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.saveddata.SavedData;
import net.minecraft.world.level.saveddata.SavedDataType;
import net.oceancanvas.mod.OceanCanvas;

import java.util.*;

/**
 * Stage 2/6 library metadata: organization and external terrain lineage. Kept separate from the core
 * vector SavedData so a broken external-asset record can never make Plan geometry unreadable.
 */
public final class OceanCanvasPlanLibraryData extends SavedData {
    public static final int CURRENT_SCHEMA=3;
    private static final Identifier DATA_ID=Identifier.fromNamespaceAndPath(OceanCanvas.MOD_ID,"plan_library");

    public record PlanGroup(String id,String name,String parentId,boolean visible,boolean locked,double opacity,String category,int drawOrder){
        public PlanGroup{id=OceanCanvasPlanLibraryData.id(id,"group");name=clean(name,"Group");parentId=opt(parentId);opacity=Math.max(0,Math.min(1,opacity));category=clean(category,"CUSTOM").toUpperCase(Locale.ROOT);}
    }
    public record ViewPreset(String id,String name,List<String> visibleGroups,List<String> hiddenGroups,List<String> visibleReferences,List<String> hiddenReferences,List<String> visibleReferenceSets,List<String> hiddenReferenceSets,String notes){
        public ViewPreset{id=OceanCanvasPlanLibraryData.id(id,"preset");name=clean(name,"View Preset");visibleGroups=ids(visibleGroups);hiddenGroups=ids(hiddenGroups);visibleReferences=ids(visibleReferences);hiddenReferences=ids(hiddenReferences);visibleReferenceSets=ids(visibleReferenceSets);hiddenReferenceSets=ids(hiddenReferenceSets);notes=notes==null?"":notes;}
        public ViewPreset(String id,String name,List<String> visibleGroups,List<String> hiddenGroups,List<String> visibleReferences,List<String> hiddenReferences,String notes){this(id,name,visibleGroups,hiddenGroups,visibleReferences,hiddenReferences,List.of(),List.of(),notes);}
        public ViewPreset(String id,String name,List<String> visibleGroups,List<String> hiddenGroups,String notes){this(id,name,visibleGroups,hiddenGroups,List.of(),List.of(),List.of(),List.of(),notes);}
    }
    public record ReferenceSet(String id,String name,List<String> referenceIds,boolean visible,boolean locked,double opacity,int drawOrder,String notes){
        public ReferenceSet{id=OceanCanvasPlanLibraryData.id(id,"refset");name=clean(name,"Reference Set");referenceIds=ids(referenceIds);opacity=Math.max(0.05,Math.min(1,opacity));notes=notes==null?"":notes;}
        public ReferenceSet(String id,String name,List<String> referenceIds,boolean visible,boolean locked,int drawOrder,String notes){this(id,name,referenceIds,visible,locked,1D,drawOrder,notes);}
    }
    public record PlanBookmark(String id,String name,int centerX,int centerZ,double zoom,String selectedObjectId,String presetId){
        public PlanBookmark{id=OceanCanvasPlanLibraryData.id(id,"bookmark");name=clean(name,"Bookmark");zoom=Math.max(.0001,Math.min(1000,zoom));selectedObjectId=opt(selectedObjectId);presetId=opt(presetId);}
    }
    public record BlueprintViewpoint(String id,String name,double x,double y,double z,float yaw,float pitch,String projection,String depth,float opacity){
        public BlueprintViewpoint{id=OceanCanvasPlanLibraryData.id(id,"viewpoint");name=clean(name,"Viewpoint");projection=clean(projection,"SEA_LEVEL").toUpperCase(Locale.ROOT);depth=clean(depth,"HYBRID").toUpperCase(Locale.ROOT);opacity=Math.max(.05F,Math.min(1F,opacity));}
    }
    public record AssetRevision(String id,String stage,String fileName,String fileHash,int minX,int minZ,int maxX,int maxZ,int widthPx,int heightPx,double blocksPerPixel,int seaLevel,String orientation,long createdAt,String notes){
        public AssetRevision{id=OceanCanvasPlanLibraryData.id(id,"revision");stage=clean(stage,"SOURCE").toUpperCase(Locale.ROOT);fileName=fileName==null?"":fileName;fileHash=fileHash==null?"":fileHash;blocksPerPixel=Math.max(0,blocksPerPixel);orientation=clean(orientation,"NORTH_UP");notes=notes==null?"":notes;}
    }
    public record TerrainAsset(String id,String name,List<String> planningObjectIds,int minX,int minZ,int maxX,int maxZ,int seaLevel,String status,List<AssetRevision> revisions,String approvedGaeaRevision,String approvedWorldPainterRevision,String placementData,String notes){
        public TerrainAsset{id=OceanCanvasPlanLibraryData.id(id,"terrain");name=clean(name,"Terrain Asset");planningObjectIds=ids(planningObjectIds);status=clean(status,"PLANNED").toUpperCase(Locale.ROOT);revisions=revisions==null?List.of():List.copyOf(revisions.stream().limit(128).toList());approvedGaeaRevision=opt(approvedGaeaRevision);approvedWorldPainterRevision=opt(approvedWorldPainterRevision);placementData=placementData==null?"":placementData;notes=notes==null?"":notes;}
        public AssetRevision revision(String rid){for(var r:revisions)if(r.id().equals(opt(rid)))return r;return null;}
    }

    private static final Codec<PlanGroup> GROUP_CODEC=RecordCodecBuilder.create(i->i.group(Codec.STRING.fieldOf("id").forGetter(PlanGroup::id),Codec.STRING.fieldOf("name").forGetter(PlanGroup::name),Codec.STRING.optionalFieldOf("parentId","").forGetter(PlanGroup::parentId),Codec.BOOL.optionalFieldOf("visible",true).forGetter(PlanGroup::visible),Codec.BOOL.optionalFieldOf("locked",false).forGetter(PlanGroup::locked),Codec.DOUBLE.optionalFieldOf("opacity",1D).forGetter(PlanGroup::opacity),Codec.STRING.optionalFieldOf("category","CUSTOM").forGetter(PlanGroup::category),Codec.INT.optionalFieldOf("drawOrder",0).forGetter(PlanGroup::drawOrder)).apply(i,PlanGroup::new));
    private static final Codec<ViewPreset> PRESET_CODEC=RecordCodecBuilder.create(i->i.group(Codec.STRING.fieldOf("id").forGetter(ViewPreset::id),Codec.STRING.fieldOf("name").forGetter(ViewPreset::name),Codec.STRING.listOf().optionalFieldOf("visibleGroups",List.of()).forGetter(ViewPreset::visibleGroups),Codec.STRING.listOf().optionalFieldOf("hiddenGroups",List.of()).forGetter(ViewPreset::hiddenGroups),Codec.STRING.listOf().optionalFieldOf("visibleReferences",List.of()).forGetter(ViewPreset::visibleReferences),Codec.STRING.listOf().optionalFieldOf("hiddenReferences",List.of()).forGetter(ViewPreset::hiddenReferences),Codec.STRING.listOf().optionalFieldOf("visibleReferenceSets",List.of()).forGetter(ViewPreset::visibleReferenceSets),Codec.STRING.listOf().optionalFieldOf("hiddenReferenceSets",List.of()).forGetter(ViewPreset::hiddenReferenceSets),Codec.STRING.optionalFieldOf("notes","").forGetter(ViewPreset::notes)).apply(i,ViewPreset::new));
    private static final Codec<ReferenceSet> REFERENCE_SET_CODEC=RecordCodecBuilder.create(i->i.group(Codec.STRING.fieldOf("id").forGetter(ReferenceSet::id),Codec.STRING.fieldOf("name").forGetter(ReferenceSet::name),Codec.STRING.listOf().optionalFieldOf("referenceIds",List.of()).forGetter(ReferenceSet::referenceIds),Codec.BOOL.optionalFieldOf("visible",true).forGetter(ReferenceSet::visible),Codec.BOOL.optionalFieldOf("locked",false).forGetter(ReferenceSet::locked),Codec.DOUBLE.optionalFieldOf("opacity",1D).forGetter(ReferenceSet::opacity),Codec.INT.optionalFieldOf("drawOrder",0).forGetter(ReferenceSet::drawOrder),Codec.STRING.optionalFieldOf("notes","").forGetter(ReferenceSet::notes)).apply(i,ReferenceSet::new));
    private static final Codec<PlanBookmark> BOOKMARK_CODEC=RecordCodecBuilder.create(i->i.group(Codec.STRING.fieldOf("id").forGetter(PlanBookmark::id),Codec.STRING.fieldOf("name").forGetter(PlanBookmark::name),Codec.INT.fieldOf("centerX").forGetter(PlanBookmark::centerX),Codec.INT.fieldOf("centerZ").forGetter(PlanBookmark::centerZ),Codec.DOUBLE.optionalFieldOf("zoom",1D).forGetter(PlanBookmark::zoom),Codec.STRING.optionalFieldOf("selectedObjectId","").forGetter(PlanBookmark::selectedObjectId),Codec.STRING.optionalFieldOf("presetId","").forGetter(PlanBookmark::presetId)).apply(i,PlanBookmark::new));
    private static final Codec<BlueprintViewpoint> VIEWPOINT_CODEC=RecordCodecBuilder.create(i->i.group(Codec.STRING.fieldOf("id").forGetter(BlueprintViewpoint::id),Codec.STRING.fieldOf("name").forGetter(BlueprintViewpoint::name),Codec.DOUBLE.fieldOf("x").forGetter(BlueprintViewpoint::x),Codec.DOUBLE.fieldOf("y").forGetter(BlueprintViewpoint::y),Codec.DOUBLE.fieldOf("z").forGetter(BlueprintViewpoint::z),Codec.FLOAT.optionalFieldOf("yaw",0F).forGetter(BlueprintViewpoint::yaw),Codec.FLOAT.optionalFieldOf("pitch",0F).forGetter(BlueprintViewpoint::pitch),Codec.STRING.optionalFieldOf("projection","SEA_LEVEL").forGetter(BlueprintViewpoint::projection),Codec.STRING.optionalFieldOf("depth","HYBRID").forGetter(BlueprintViewpoint::depth),Codec.FLOAT.optionalFieldOf("opacity",.72F).forGetter(BlueprintViewpoint::opacity)).apply(i,BlueprintViewpoint::new));
    private static final Codec<AssetRevision> REV_CODEC=RecordCodecBuilder.create(i->i.group(Codec.STRING.fieldOf("id").forGetter(AssetRevision::id),Codec.STRING.fieldOf("stage").forGetter(AssetRevision::stage),Codec.STRING.optionalFieldOf("fileName","").forGetter(AssetRevision::fileName),Codec.STRING.optionalFieldOf("fileHash","").forGetter(AssetRevision::fileHash),Codec.INT.fieldOf("minX").forGetter(AssetRevision::minX),Codec.INT.fieldOf("minZ").forGetter(AssetRevision::minZ),Codec.INT.fieldOf("maxX").forGetter(AssetRevision::maxX),Codec.INT.fieldOf("maxZ").forGetter(AssetRevision::maxZ),Codec.INT.optionalFieldOf("widthPx",0).forGetter(AssetRevision::widthPx),Codec.INT.optionalFieldOf("heightPx",0).forGetter(AssetRevision::heightPx),Codec.DOUBLE.optionalFieldOf("blocksPerPixel",0D).forGetter(AssetRevision::blocksPerPixel),Codec.INT.optionalFieldOf("seaLevel",63).forGetter(AssetRevision::seaLevel),Codec.STRING.optionalFieldOf("orientation","NORTH_UP").forGetter(AssetRevision::orientation),Codec.LONG.optionalFieldOf("createdAt",0L).forGetter(AssetRevision::createdAt),Codec.STRING.optionalFieldOf("notes","").forGetter(AssetRevision::notes)).apply(i,AssetRevision::new));
    private static final Codec<TerrainAsset> TERRAIN_CODEC=RecordCodecBuilder.create(i->i.group(Codec.STRING.fieldOf("id").forGetter(TerrainAsset::id),Codec.STRING.fieldOf("name").forGetter(TerrainAsset::name),Codec.STRING.listOf().optionalFieldOf("planningObjectIds",List.of()).forGetter(TerrainAsset::planningObjectIds),Codec.INT.fieldOf("minX").forGetter(TerrainAsset::minX),Codec.INT.fieldOf("minZ").forGetter(TerrainAsset::minZ),Codec.INT.fieldOf("maxX").forGetter(TerrainAsset::maxX),Codec.INT.fieldOf("maxZ").forGetter(TerrainAsset::maxZ),Codec.INT.optionalFieldOf("seaLevel",63).forGetter(TerrainAsset::seaLevel),Codec.STRING.optionalFieldOf("status","PLANNED").forGetter(TerrainAsset::status),REV_CODEC.listOf().optionalFieldOf("revisions",List.of()).forGetter(TerrainAsset::revisions),Codec.STRING.optionalFieldOf("approvedGaeaRevision","").forGetter(TerrainAsset::approvedGaeaRevision),Codec.STRING.optionalFieldOf("approvedWorldPainterRevision","").forGetter(TerrainAsset::approvedWorldPainterRevision),Codec.STRING.optionalFieldOf("placementData","").forGetter(TerrainAsset::placementData),Codec.STRING.optionalFieldOf("notes","").forGetter(TerrainAsset::notes)).apply(i,TerrainAsset::new));
    private static final Codec<OceanCanvasPlanLibraryData> CODEC=RecordCodecBuilder.create(i->i.group(Codec.INT.optionalFieldOf("schema",CURRENT_SCHEMA).forGetter(d->d.schema),GROUP_CODEC.listOf().optionalFieldOf("groups",List.of()).forGetter(d->new ArrayList<>(d.groups.values())),PRESET_CODEC.listOf().optionalFieldOf("presets",List.of()).forGetter(d->new ArrayList<>(d.presets.values())),BOOKMARK_CODEC.listOf().optionalFieldOf("bookmarks",List.of()).forGetter(d->new ArrayList<>(d.bookmarks.values())),TERRAIN_CODEC.listOf().optionalFieldOf("terrainAssets",List.of()).forGetter(d->new ArrayList<>(d.terrainAssets.values())),REFERENCE_SET_CODEC.listOf().optionalFieldOf("referenceSets",List.of()).forGetter(d->new ArrayList<>(d.referenceSets.values())),VIEWPOINT_CODEC.listOf().optionalFieldOf("viewpoints",List.of()).forGetter(d->new ArrayList<>(d.viewpoints.values()))).apply(i,OceanCanvasPlanLibraryData::new));
    public static final SavedDataType<OceanCanvasPlanLibraryData> TYPE=new SavedDataType<>(DATA_ID,OceanCanvasPlanLibraryData::new,CODEC,null);

    private int schema;private final Map<String,PlanGroup> groups=new LinkedHashMap<>();private final Map<String,ViewPreset> presets=new LinkedHashMap<>();private final Map<String,PlanBookmark> bookmarks=new LinkedHashMap<>();private final Map<String,TerrainAsset> terrainAssets=new LinkedHashMap<>();private final Map<String,ReferenceSet> referenceSets=new LinkedHashMap<>();private final Map<String,BlueprintViewpoint> viewpoints=new LinkedHashMap<>();
    public OceanCanvasPlanLibraryData(){this(CURRENT_SCHEMA,List.of(),List.of(),List.of(),List.of(),List.of(),List.of());}
    private OceanCanvasPlanLibraryData(int schema,List<PlanGroup> groups,List<ViewPreset> presets,List<PlanBookmark> bookmarks,List<TerrainAsset> terrain,List<ReferenceSet> referenceSets,List<BlueprintViewpoint> viewpoints){this.schema=Math.max(1,schema);groups.forEach(v->this.groups.put(v.id(),v));presets.forEach(v->this.presets.put(v.id(),v));bookmarks.forEach(v->this.bookmarks.put(v.id(),v));terrain.forEach(v->this.terrainAssets.put(v.id(),v));referenceSets.forEach(v->this.referenceSets.put(v.id(),v));viewpoints.forEach(v->this.viewpoints.put(v.id(),v));installDefaults();}
    private void installDefaults(){String[] cats={"Coastline","Mountains","Rivers","Lakes","Biomes","Settlements","Transportation","Borders","Notes"};int i=0;for(String c:cats){String key=c.toLowerCase(Locale.ROOT);groups.putIfAbsent(key,new PlanGroup(key,c,"",true,false,1D,c.toUpperCase(Locale.ROOT),i++));}presets.putIfAbsent("physical_geography",new ViewPreset("physical_geography","Physical Geography",List.of("coastline","mountains","rivers","lakes","biomes"),List.of(),""));presets.putIfAbsent("civilization",new ViewPreset("civilization","Civilization",List.of("settlements","transportation","borders"),List.of(),""));}
    public static OceanCanvasPlanLibraryData get(ServerLevel world){return world.getDataStorage().computeIfAbsent(TYPE);} public int schema(){return schema;}
    public List<PlanGroup> groups(){return List.copyOf(groups.values());}public List<ViewPreset> presets(){return List.copyOf(presets.values());}public List<PlanBookmark> bookmarks(){return List.copyOf(bookmarks.values());}public List<TerrainAsset> terrainAssets(){return List.copyOf(terrainAssets.values());}public List<ReferenceSet> referenceSets(){return List.copyOf(referenceSets.values());}public List<BlueprintViewpoint> viewpoints(){return List.copyOf(viewpoints.values());}
    public PlanGroup group(String id){return groups.get(opt(id));}public ViewPreset preset(String id){return presets.get(opt(id));}public PlanBookmark bookmark(String id){return bookmarks.get(opt(id));}public TerrainAsset terrainAsset(String id){return terrainAssets.get(opt(id));}public ReferenceSet referenceSet(String id){return referenceSets.get(opt(id));}public BlueprintViewpoint viewpoint(String id){return viewpoints.get(opt(id));}
    public String newId(String prefix){return id(prefix+"_"+UUID.randomUUID().toString().substring(0,8),prefix);}public void putViewpoint(BlueprintViewpoint v){viewpoints.put(v.id(),v);setDirty();}public boolean removeViewpoint(String id){boolean c=viewpoints.remove(opt(id))!=null;if(c)setDirty();return c;}public void putGroup(PlanGroup v){groups.put(v.id(),v);setDirty();}public void putPreset(ViewPreset v){presets.put(v.id(),v);setDirty();}public void putBookmark(PlanBookmark v){bookmarks.put(v.id(),v);setDirty();}public void putTerrainAsset(TerrainAsset v){terrainAssets.put(v.id(),v);setDirty();}public void putReferenceSet(ReferenceSet v){referenceSets.put(v.id(),v);setDirty();}
    public boolean removeTerrainAsset(String id){boolean c=terrainAssets.remove(opt(id))!=null;if(c)setDirty();return c;}public boolean removeBookmark(String id){boolean c=bookmarks.remove(opt(id))!=null;if(c)setDirty();return c;}public boolean removePreset(String id){boolean c=presets.remove(opt(id))!=null;if(c)setDirty();return c;}public boolean removeReferenceSet(String id){boolean c=referenceSets.remove(opt(id))!=null;if(c)setDirty();return c;}
    public boolean wouldCreateGroupCycle(String groupId,String parentId){String child=opt(groupId),cur=opt(parentId);java.util.HashSet<String> seen=new java.util.HashSet<>();while(!cur.isBlank()&&seen.add(cur)){if(cur.equals(child))return true;PlanGroup p=groups.get(cur);if(p==null)break;cur=p.parentId();}return false;}
    private static List<String> ids(List<String> v){if(v==null)return List.of();return v.stream().map(OceanCanvasPlanLibraryData::opt).filter(s->!s.isBlank()).distinct().limit(128).toList();}
    private static String clean(String v,String f){return v==null||v.isBlank()?f:v.trim();}private static String opt(String v){return v==null?"":v.trim().toLowerCase(Locale.ROOT).replace(' ','_');}private static String id(String v,String f){String s=opt(v);return s.isBlank()?f:s;}
}
