package net.oceancanvas.mod.project;

import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.storage.LevelResource;
import net.oceancanvas.mod.OceanCanvas;
import net.oceancanvas.mod.config.OceanCanvasConfig;
import net.oceancanvas.mod.project.OceanCanvasHarnessService;
import net.oceancanvas.mod.operation.OceanCanvasOperationHistoryData;
import net.oceancanvas.mod.worldgen.OceanCanvasPlayerZones;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.stream.Stream;

/** Shared, bounded P1-W4 stewardship/project-maintenance services. */
public final class OceanCanvasP1W4Service {
    private OceanCanvasP1W4Service(){}

    public record ScaleDashboard(OceanCanvasP1W4Data.WorldScaleSnapshot current,OceanCanvasP1W4Data.WorldScaleSnapshot previous,String delta){}
    public record StorageForecast(OceanCanvasP1W4Data.StorageSample current,long dailyGrowth,long projected30Days,long projected365Days,String confidence,String detail){}
    public record UpgradeDiff(String state,OceanCanvasP1W4Data.UpgradeSnapshot baseline,OceanCanvasP1W4Data.UpgradeSnapshot current,List<String> changes,String confidence){}
    public record LayerNode(String id,String type,String label){} public record LayerEdge(String from,String to,String relation){} public record LayerGraph(List<LayerNode> nodes,List<LayerEdge> edges,int missingReferences,String detail){}
    public record PermissionMatrix(boolean viewPlans,boolean editPlans,boolean manageProjects,boolean destructiveOps,boolean diagnostics,boolean admin){}

    public static OceanCanvasP1W4Data.WorldScaleSnapshot currentScale(ServerLevel world){
        var zones=OceanCanvasPlayerZones.get(world).all();Set<Long> defined=new HashSet<>(),reserved=new HashSet<>(),protectedChunks=new HashSet<>();
        var project=OceanCanvasProjectData.get(world);
        for(var z:zones){defined.addAll(z.exactChunks());if(z.protectedNow())protectedChunks.addAll(z.exactChunks());var meta=project.regionMeta(z.name());if(meta!=null&&meta.parsedStage()==OceanCanvasProjectData.RegionStage.RESERVED)reserved.addAll(z.exactChunks());}
        // v253.125.38: terrain-state counts are maintained incrementally. The scale
        // dashboard needs only counts, so do not materialize/box every explicit chunk.
        var states=OceanCanvasTerrainStateData.get(world);long explicit=states.explicitStateCount();
        long canvas=states.stateCount(OceanCanvasTerrainStateData.TerrainState.CANVAS),restored=states.stateCount(OceanCanvasTerrainStateData.TerrainState.VANILLA),modified=states.stateCount(OceanCanvasTerrainStateData.TerrainState.CUSTOM_OR_MODIFIED);
        long side=Math.max(1L,(OceanCanvasConfig.get().canvasSize()+15L)/16L),total=side*side,untouched=Math.max(0,total-explicit);String detail="Canvas estimate="+total+" chunks; explicit terrain-state evidence="+explicit+"; Used means explicit Canvas/Restored/Modified evidence, not player activity.";
        return new OceanCanvasP1W4Data.WorldScaleSnapshot("current",System.currentTimeMillis(),defined.size(),reserved.size(),protectedChunks.size(),canvas,restored,modified,untouched,detail);
    }
    public static ScaleDashboard captureScale(ServerLevel world){
        var data=OceanCanvasP1W4Data.get(world);var current=currentScale(world);var previous=data.scale().stream().findFirst().orElse(null);var snap=new OceanCanvasP1W4Data.WorldScaleSnapshot(data.newId("scale"),current.epochMillis(),current.definedChunks(),current.reservedChunks(),current.protectedChunks(),current.canvasChunks(),current.restoredChunks(),current.modifiedChunks(),current.untouchedEstimate(),current.detail());data.putScale(snap);String delta=previous==null?"Initial scale snapshot.":"Since previous: Canvas "+signed(snap.canvasChunks()-previous.canvasChunks())+", restored "+signed(snap.restoredChunks()-previous.restoredChunks())+", modified "+signed(snap.modifiedChunks()-previous.modifiedChunks())+", reserved "+signed(snap.reservedChunks()-previous.reservedChunks())+".";return new ScaleDashboard(snap,previous,delta);
    }

    public static OceanCanvasP1W4Data.RetirementRecord retireProject(ServerLevel world,String projectId,String mode,String requester,String note){
        var workspace=OceanCanvasWorkspaceData.get(world);var p=workspace.project(projectId);if(p==null)throw new IllegalArgumentException("unknown project");String m=upper(mode,"ARCHIVE_ONLY");if(!Set.of("ARCHIVE_ONLY","LEAVE_RUINS","RESTORE_REGION").contains(m))throw new IllegalArgumentException("retirement mode must be ARCHIVE_ONLY, LEAVE_RUINS or RESTORE_REGION");long now=System.currentTimeMillis();String state=m.equals("RESTORE_REGION")&&!p.regionName().isBlank()?"AWAITING_CONFIRMATION":"COMPLETE";
        workspace.putProject(new OceanCanvasWorkspaceData.WorkProject(p.id(),p.name(),p.parentProjectId(),p.planningObjectIds(),p.terrainAssetIds(),p.regionName(),"ARCHIVED",p.templateId(),p.notes(),p.milestones(),p.createdAt(),now,p.phases(),p.blockers(),p.currentTaskId(),p.milestoneRecords()));
        var d=OceanCanvasP1W4Data.get(world);var r=new OceanCanvasP1W4Data.RetirementRecord(d.newId("retirement"),"PROJECT",p.id(),m,state,requester,now,now,note+(state.equals("AWAITING_CONFIRMATION")?" Normal Restore preview/confirmation is required for Region '"+p.regionName()+"'.":""));d.putRetirement(r);workspace.addJournal("Retired project '"+p.name()+"' using "+m,p.regionName(),0,0);return r;
    }
    public static void refreshRetirements(ServerLevel world){var d=OceanCanvasP1W4Data.get(world);for(var r:d.retirements()){if(!r.state().equals("AWAITING_CONFIRMATION")||!r.mode().equals("RESTORE_REGION"))continue;var p=OceanCanvasWorkspaceData.get(world).project(r.subjectId());if(p==null||p.regionName().isBlank())continue;for(var h:OceanCanvasOperationHistoryData.get(world).recent()){if(h.kind().equalsIgnoreCase("RESTORE")&&h.phase().equalsIgnoreCase("COMPLETED")&&h.scopeId().equalsIgnoreCase(p.regionName())&&h.epochMillis()>=r.createdAt()){d.putRetirement(new OceanCanvasP1W4Data.RetirementRecord(r.id(),r.subjectType(),r.subjectId(),r.mode(),"COMPLETE",r.requestedBy(),r.createdAt(),System.currentTimeMillis(),r.note()+" Restore completed through normal operation lifecycle."));break;}}}}

    public static OceanCanvasP1W4Data.ReviewItem addReview(ServerLevel world,String type,String subjectId,String label,String author,String comment){String t=upper(type,"PROJECT");validateSubject(world,t,subjectId);var d=OceanCanvasP1W4Data.get(world);long now=System.currentTimeMillis();var r=new OceanCanvasP1W4Data.ReviewItem(d.newId("review"),t,subjectId,label,"OPEN",author,comment,now,now);d.putReview(r);return r;}
    public static OceanCanvasP1W4Data.ReviewItem decideReview(ServerLevel world,String id,String state,String author,String comment){var d=OceanCanvasP1W4Data.get(world);var old=d.review(id);if(old==null)throw new IllegalArgumentException("unknown review item");String s=upper(state,"OPEN");if(!Set.of("OPEN","APPROVED","CHANGES_REQUESTED","REJECTED","CLOSED").contains(s))throw new IllegalArgumentException("invalid review decision");var next=new OceanCanvasP1W4Data.ReviewItem(old.id(),old.subjectType(),old.subjectId(),old.label(),s,author,comment.isBlank()?old.comment():comment,old.createdAt(),System.currentTimeMillis());d.putReview(next);return next;}

    public static OceanCanvasP1W4Data.SessionPlan generateSessionPlan(ServerPlayer player,int availableMinutes){ServerLevel world=player.level();var work=OceanCanvasWorkspaceData.get(world);int minutes=Math.max(5,Math.min(720,availableMinutes));BlockPos here=player.blockPosition();recordRecentContext(world,"PLACE","session_start","Session start",here.getX(),here.getZ());
        record Candidate(OceanCanvasWorkspaceData.GeoTask task,double score,int minutes,String rationale){} var candidates=new ArrayList<Candidate>();int materialBlocked=0;
        for(var t:work.tasks()){if(t.terminal()||t.parsedStatus()==OceanCanvasWorkspaceData.TaskStatus.BLOCKED||t.parsedStatus()==OceanCanvasWorkspaceData.TaskStatus.IN_PROGRESS)continue;var p=t.projectId().isBlank()?null:work.project(t.projectId());if(p!=null&&p.parsedStatus()==OceanCanvasWorkspaceData.ProjectStatus.ARCHIVED)continue;boolean materialsReady=true;for(var c:t.checklist())if(c.text().trim().toUpperCase(Locale.ROOT).startsWith("MATERIAL:")&&!c.complete())materialsReady=false;if(!materialsReady){materialBlocked++;continue;}int estimate=Math.max(5,Math.min(120,(int)Math.round(t.weight()*15.0)));double dist=Math.hypot(t.x()-here.getX(),t.z()-here.getZ());double score=t.priority()*1000.0+(t.parsedStatus()==OceanCanvasWorkspaceData.TaskStatus.READY?500:0)+(p!=null&&p.id().equals(work.activeWorkProject())?250:0)-dist/16.0-estimate;String why="priority="+t.priority()+", "+(t.parsedStatus()==OceanCanvasWorkspaceData.TaskStatus.READY?"ready":"planned")+", distance="+(int)dist+" blocks, estimate="+estimate+"m";candidates.add(new Candidate(t,score,estimate,why));}
        candidates.sort(Comparator.comparingDouble(Candidate::score).reversed());List<String> chosen=new ArrayList<>();int used=0;StringBuilder rationale=new StringBuilder();for(var c:candidates){if(chosen.size()>=12)break;if(used+c.minutes()>minutes&& !chosen.isEmpty())continue;chosen.add(c.task().id());used+=c.minutes();if(rationale.length()>0)rationale.append(" | ");rationale.append(c.task().title()).append(": ").append(c.rationale());}
        if(chosen.isEmpty()&&!candidates.isEmpty()){chosen.add(candidates.get(0).task().id());used=candidates.get(0).minutes();rationale.append("Nearest/highest priority candidate exceeds requested time but is shown as the best next task.");}
        if(materialBlocked>0)rationale.append(rationale.length()>0?" | ":"").append(materialBlocked).append(" task(s) excluded because an incomplete checklist item starts with MATERIAL:.");var d=OceanCanvasP1W4Data.get(world);long now=System.currentTimeMillis();var plan=new OceanCanvasP1W4Data.SessionPlan(d.newId("session_plan"),"Session "+Instant.ofEpochMilli(now),minutes,"PLANNED",chosen,0,now,now,rationale.toString());d.putSessionPlan(plan);return plan;}
    public static OceanCanvasP1W4Data.SessionPlan advanceSessionPlan(ServerLevel world,String id,String action){var d=OceanCanvasP1W4Data.get(world);var p=d.sessionPlans().stream().filter(v->v.id().equals(id)).findFirst().orElse(null);if(p==null)throw new IllegalArgumentException("unknown session plan");String a=upper(action,"START");String state=p.state();int cursor=p.cursor();if(a.equals("START")){if(!Set.of("PLANNED","PAUSED").contains(state))throw new IllegalArgumentException("session plan cannot start from "+state);state="ACTIVE";}else if(a.equals("PAUSE")){if(!state.equals("ACTIVE"))throw new IllegalArgumentException("only an active session plan can pause");state="PAUSED";}else if(a.equals("NEXT")){if(!state.equals("ACTIVE"))throw new IllegalArgumentException("start the session plan before advancing");cursor=Math.min(p.taskIds().size(),cursor+1);if(cursor>=p.taskIds().size())state="COMPLETE";}else if(a.equals("CANCEL")){state="CANCELLED";}else throw new IllegalArgumentException("unsupported session action");var next=new OceanCanvasP1W4Data.SessionPlan(p.id(),p.label(),p.availableMinutes(),state,p.taskIds(),cursor,p.createdAt(),System.currentTimeMillis(),p.rationale());d.putSessionPlan(next);return next;}

    public static StorageForecast storageForecast(ServerLevel world){var history=OceanCanvasP1W4Data.get(world).storage();if(history.isEmpty())return new StorageForecast(new OceanCanvasP1W4Data.StorageSample(0,0,0,0,0,0),0,0,0,"UNVERIFIED","No storage sample captured yet.");var newest=history.get(0);long daily=0;String conf="UNVERIFIED",detail="Need at least two samples separated by time for a growth rate.";if(history.size()>=2){var oldest=history.get(history.size()-1);long dt=Math.max(1,newest.epochMillis()-oldest.epochMillis()),delta=newest.totalBytes()-oldest.totalBytes();daily=Math.max(0,Math.round(delta*86_400_000.0/dt));conf=dt>=86_400_000L?"AUTHORITATIVE_TREND":"SHORT_WINDOW";detail="Observed "+formatBytes(Math.max(0,delta))+" growth over "+String.format(Locale.ROOT,"%.1f",dt/3_600_000.0)+" hours; projection is linear and advisory.";}return new StorageForecast(newest,daily,newest.totalBytes()+daily*30,newest.totalBytes()+daily*365,conf,detail);}

    public static StorageForecast sampleStorage(ServerLevel world){Path root=world.getServer().getWorldPath(LevelResource.ROOT);long region=sizeBounded(root.resolve("region"),4,10000),poi=sizeBounded(root.resolve("poi"),4,10000),entities=sizeBounded(root.resolve("entities"),4,10000),oc=sizeBounded(root.resolve("oceancanvas"),8,20000)+sizeOceanCanvasSavedData(root.resolve("data"));long total=region+poi+entities+oc;var d=OceanCanvasP1W4Data.get(world);var sample=new OceanCanvasP1W4Data.StorageSample(System.currentTimeMillis(),total,oc,region,poi,entities);d.putStorage(sample);return storageForecast(world);}

    public static void recordRecentContext(ServerLevel world,String type,String id,String label,int x,int z){OceanCanvasP1W4Data.get(world).touchContext(type,id,label,x,z);}
    public static OceanCanvasP1W4Data.MaintenanceItem completeMaintenance(ServerLevel world,String id){var d=OceanCanvasP1W4Data.get(world);var m=d.maintenance(id);if(m==null)throw new IllegalArgumentException("unknown maintenance item");long now=System.currentTimeMillis(),next=now+m.cadenceDays()*86_400_000L;var n=new OceanCanvasP1W4Data.MaintenanceItem(m.id(),m.label(),m.cadenceDays(),now,next,"SCHEDULED",m.note());d.putMaintenance(n);return n;}
    public static void refreshMaintenance(ServerLevel world){var d=OceanCanvasP1W4Data.get(world);long now=System.currentTimeMillis();for(var m:d.maintenance())if(now>=m.nextDueAt()&&!m.state().equals("DUE"))d.putMaintenance(new OceanCanvasP1W4Data.MaintenanceItem(m.id(),m.label(),m.cadenceDays(),m.lastCompletedAt(),m.nextDueAt(),"DUE",m.note()));}

    public static UpgradeDiff upgradeDiff(ServerLevel world){var d=OceanCanvasP1W4Data.get(world);var current=currentUpgrade(world);var baseline=d.latestUpgrade();if(baseline==null)return new UpgradeDiff("UNVERIFIED",null,current,List.of("No accepted upgrade baseline. Capture the current environment before/after migration to make registry/data-version changes auditable."),"UNVERIFIED");List<String> changes=new ArrayList<>();if(!baseline.minecraftVersion().equals(current.minecraftVersion()))changes.add("Minecraft "+baseline.minecraftVersion()+" → "+current.minecraftVersion());if(!baseline.compatibilitySignature().equals(current.compatibilitySignature()))changes.add("Fabric/dependency compatibility signature changed");if(!baseline.datapackSignature().equals(current.datapackSignature()))changes.add("Selected datapack/worldgen signature changed");if(baseline.biomeCount()!=current.biomeCount())changes.add("Observed managed-area biome IDs "+baseline.biomeCount()+" → "+current.biomeCount());if(baseline.structureCount()!=current.structureCount())changes.add("Observed managed-area structure kinds "+baseline.structureCount()+" → "+current.structureCount());if(baseline.poiTypeCount()!=current.poiTypeCount())changes.add("Loaded modified-area POI records "+baseline.poiTypeCount()+" → "+current.poiTypeCount());String state=changes.isEmpty()?"MATCH":"CHANGED";return new UpgradeDiff(state,baseline,current,List.copyOf(changes),"AUTHORITATIVE_METADATA");}
    public static UpgradeDiff acceptUpgradeBaseline(ServerLevel world){var d=OceanCanvasP1W4Data.get(world);d.putUpgrade(currentUpgrade(world));return upgradeDiff(world);}
    private static OceanCanvasP1W4Data.UpgradeSnapshot currentUpgrade(ServerLevel world){var p1=OceanCanvasP1W3Data.get(world);int biomes=(int)p1.chunks().stream().map(OceanCanvasP1W3Data.ChunkEvidence::biomeId).filter(v->!v.isBlank()).distinct().count();OceanCanvasP1W3Service.syncStructureEvidence(world);int structures=(int)p1.structures().stream().map(OceanCanvasP1W3Data.StructureEvidence::kind).distinct().count();var poi=OceanCanvasP1W3Service.poiIntegrity(world,64);String compat=OceanCanvasHarnessService.compatibilitySignature(world),dp=OceanCanvasP1W3Service.datapackStatus(world).currentSignature();String detail="schemas workspace="+OceanCanvasWorkspaceData.CURRENT_SCHEMA+", project="+OceanCanvasProjectData.CURRENT_SCHEMA+", terrain="+OceanCanvasTerrainStateData.CURRENT_SCHEMA+", p1w3="+OceanCanvasP1W3Data.CURRENT_SCHEMA+", p1w4="+OceanCanvasP1W4Data.CURRENT_SCHEMA+"; managed-area counts are bounded observed evidence, not claims about every vanilla registry entry.";var d=OceanCanvasP1W4Data.get(world);return new OceanCanvasP1W4Data.UpgradeSnapshot(d.newId("upgrade"),OceanCanvasP1W3Service.minecraftVersion(),compat,dp,biomes,structures,poi.poiRecords(),System.currentTimeMillis(),detail);}

    public static LayerGraph layerGraph(ServerLevel world){var nodes=new LinkedHashMap<String,LayerNode>();var edges=new ArrayList<LayerEdge>();int missing=0;var zones=OceanCanvasPlayerZones.get(world);for(var z:zones.all())nodes.put("REGION:"+z.name().toLowerCase(Locale.ROOT),new LayerNode("REGION:"+z.name(),"REGION",z.name()));var plan=OceanCanvasPlanningData.get(world);for(var o:plan.objects())nodes.put("PLAN:"+o.id(),new LayerNode("PLAN:"+o.id(),"PLAN",o.name()));for(var r:plan.referenceLayers())nodes.put("REFERENCE:"+r.id(),new LayerNode("REFERENCE:"+r.id(),"REFERENCE",r.name()));var lib=OceanCanvasPlanLibraryData.get(world);for(var a:lib.terrainAssets())nodes.put("TERRAIN:"+a.id(),new LayerNode("TERRAIN:"+a.id(),"TERRAIN_ASSET",a.name()));for(var set:lib.referenceSets()){String sid="REFERENCE_SET:"+set.id();nodes.put(sid,new LayerNode(sid,"REFERENCE_SET",set.name()));for(String rid:set.referenceIds()){String to="REFERENCE:"+rid;if(nodes.containsKey(to))edges.add(new LayerEdge(sid,to,"contains"));else missing++;}}
        for(var p:OceanCanvasWorkspaceData.get(world).projects()){String pid="PROJECT:"+p.id();nodes.put(pid,new LayerNode(pid,"PROJECT",p.name()));if(!p.regionName().isBlank()){String to="REGION:"+p.regionName().toLowerCase(Locale.ROOT);if(nodes.containsKey(to))edges.add(new LayerEdge(pid,to,"scoped-to"));else missing++;}for(String id:p.planningObjectIds()){String to="PLAN:"+id;if(nodes.containsKey(to))edges.add(new LayerEdge(pid,to,"implements"));else missing++;}for(String id:p.terrainAssetIds()){String to="TERRAIN:"+id;if(nodes.containsKey(to))edges.add(new LayerEdge(pid,to,"uses"));else missing++;}}
        return new LayerGraph(List.copyOf(nodes.values()),List.copyOf(edges),missing,"Derived read-only graph from stable IDs; missing references are reported rather than repaired automatically.");}

    public static PermissionMatrix permissions(ServerPlayer player){var src=player.createCommandSourceStack();return new PermissionMatrix(
            me.lucko.fabric.api.permissions.v0.Permissions.require("oceancanvas.planning.view",1).test(src),
            me.lucko.fabric.api.permissions.v0.Permissions.require("oceancanvas.planning.edit",1).test(src),
            me.lucko.fabric.api.permissions.v0.Permissions.require("oceancanvas.project.manage",1).test(src),
            me.lucko.fabric.api.permissions.v0.Permissions.require("oceancanvas.protect",2).test(src),
            me.lucko.fabric.api.permissions.v0.Permissions.require("oceancanvas.diagnostics.view",1).test(src),
            me.lucko.fabric.api.permissions.v0.Permissions.require("oceancanvas.admin",2).test(src));}

    public static String headlessReport(ServerLevel world){refreshRetirements(world);refreshMaintenance(world);var scale=captureScale(world);var storage=sampleStorage(world);var upgrade=upgradeDiff(world);var health=OceanCanvasWorldHealthScorecard.snapshot(world);var assets=OceanCanvasAssetIntegrityService.scan(world,32);var graph=layerGraph(world);var d=OceanCanvasP1W4Data.get(world);long openReviews=d.reviews().stream().filter(v->v.state().equals("OPEN")||v.state().equals("CHANGES_REQUESTED")).count(),due=d.maintenance().stream().filter(v->v.state().equals("DUE")).count();StringBuilder s=new StringBuilder();s.append("Ocean Canvas headless report\n").append("build=").append(OceanCanvas.VERSION).append(" minecraft=").append(OceanCanvasP1W3Service.minecraftVersion()).append('\n');s.append("worldScale defined=").append(scale.current().definedChunks()).append(" reserved=").append(scale.current().reservedChunks()).append(" protected=").append(scale.current().protectedChunks()).append(" canvas=").append(scale.current().canvasChunks()).append(" restored=").append(scale.current().restoredChunks()).append(" modified=").append(scale.current().modifiedChunks()).append(" untouchedEstimate=").append(scale.current().untouchedEstimate()).append('\n');s.append("storage current=").append(formatBytes(storage.current().totalBytes())).append(" dailyGrowth=").append(formatBytes(storage.dailyGrowth())).append(" projected365=").append(formatBytes(storage.projected365Days())).append(" confidence=").append(storage.confidence()).append('\n');s.append("upgrade=").append(upgrade.state()).append(" changes=").append(upgrade.changes().isEmpty()?"none":String.join(" | ",upgrade.changes())).append('\n');s.append("workflow projects=").append(OceanCanvasWorkspaceData.get(world).projects().size()).append(" tasks=").append(OceanCanvasWorkspaceData.get(world).tasks().size()).append(" brokenLinks=").append(assets.issues()).append(" openReviews=").append(openReviews).append(" maintenanceDue=").append(due).append('\n');s.append("layerGraph nodes=").append(graph.nodes().size()).append(" edges=").append(graph.edges().size()).append(" missingRefs=").append(graph.missingReferences()).append('\n');for(var c:health.components())s.append("health.").append(c.id()).append('=').append(c.state()).append(" :: ").append(c.detail()).append('\n');return s.toString();}

    private static void validateSubject(ServerLevel world,String type,String id){switch(type){case "PROJECT"->{if(OceanCanvasWorkspaceData.get(world).project(id)==null)throw new IllegalArgumentException("unknown project");}case "PLAN"->{if(OceanCanvasPlanningData.get(world).object(id)==null)throw new IllegalArgumentException("unknown plan object");}case "REGION"->{if(OceanCanvasPlayerZones.get(world).zoneByName(id)==null)throw new IllegalArgumentException("unknown region");}case "MILESTONE"->{if(id==null||id.isBlank())throw new IllegalArgumentException("milestone ID required");}default->throw new IllegalArgumentException("review subject must be PROJECT, PLAN, REGION or MILESTONE");}}
    private static long sizeBounded(Path root,int depth,long maxFiles){if(root==null||!Files.exists(root))return 0L;try(Stream<Path> s=Files.walk(root,depth)){return s.filter(Files::isRegularFile).limit(maxFiles).mapToLong(p->{try{return Files.size(p);}catch(IOException e){return 0L;}}).sum();}catch(IOException e){return 0L;}}
    private static long sizeOceanCanvasSavedData(Path data){if(data==null||!Files.isDirectory(data))return 0L;try(Stream<Path>s=Files.list(data)){return s.filter(Files::isRegularFile).filter(p->p.getFileName().toString().toLowerCase(Locale.ROOT).contains("oceancanvas")).limit(2048).mapToLong(p->{try{return Files.size(p);}catch(IOException e){return 0L;}}).sum();}catch(IOException e){return 0L;}}
    public static String formatBytes(long v){double n=Math.max(0,v);String[] u={"B","KiB","MiB","GiB","TiB"};int i=0;while(n>=1024&&i<u.length-1){n/=1024;i++;}return String.format(Locale.ROOT,i==0?"%.0f %s":"%.1f %s",n,u[i]);}
    private static String upper(String s,String fallback){String v=s==null?"":s.trim();return (v.isBlank()?fallback:v).toUpperCase(Locale.ROOT);} private static String signed(long n){return n>=0?"+"+n:Long.toString(n);}
}
