package net.oceancanvas.mod.project;

import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.storage.LevelResource;
import net.oceancanvas.mod.OceanCanvas;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

/** Portable, non-terrain Stage-8 project package. Import/merge is intentionally a separate operation. */
public final class OceanCanvasProjectPackageExporter {
    private OceanCanvasProjectPackageExporter() { }
    private static final DateTimeFormatter STAMP=DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss", Locale.ROOT).withZone(ZoneOffset.UTC);
    public record Result(Path file,int tasks,int planObjects,int terrainAssets) { }

    public static Result export(ServerLevel world,String projectId) throws IOException {
        var work=OceanCanvasWorkspaceData.get(world); var project=work.project(projectId);
        if(project==null)throw new IllegalArgumentException("Unknown project: "+projectId);
        var plan=OceanCanvasPlanningData.get(world); var lib=OceanCanvasPlanLibraryData.get(world);
        var tasks=work.tasks().stream().filter(t->t.projectId().equals(project.id())).toList();
        var planObjects=project.planningObjectIds().stream().map(plan::object).filter(java.util.Objects::nonNull).toList();
        var terrain=project.terrainAssetIds().stream().map(lib::terrainAsset).filter(java.util.Objects::nonNull).toList();
        var checkpoints=OceanCanvasPipelineSnapshotData.get(world).recent(project.id());
        Path root=world.getServer().getWorldPath(LevelResource.ROOT).resolve("oceancanvas").resolve("projects");Files.createDirectories(root);
        Path file=root.resolve(safe(project.name())+"-"+STAMP.format(Instant.now())+".oceanproject");
        try(ZipOutputStream zip=new ZipOutputStream(Files.newOutputStream(file),StandardCharsets.UTF_8)){
            write(zip,"manifest.json",json(project,tasks,planObjects,terrain,checkpoints));
            write(zip,"atlas-index.json",atlasJsonWithChapters(world,project));
            write(zip,"ATLAS.md",atlasMarkdownWithChapters(world,project));
            write(zip,"atlas-map.svg",atlasSvg(world,project));
            write(zip,"schema/oceancanvas-project-v4.schema.json",net.oceancanvas.mod.planning.OceanCanvasP5PipelineService.interchangeSchemaJson());
            write(zip,"pipeline/coordinate-contract.txt",net.oceancanvas.mod.planning.OceanCanvasP5PipelineService.coordinateContractText());
            write(zip,"pipeline/transforms.json",net.oceancanvas.mod.planning.OceanCanvasP5PipelineService.transformsJson(world));
            write(zip,"pipeline/export-recipes.json",net.oceancanvas.mod.planning.OceanCanvasP5PipelineService.recipesJson(world));
            write(zip,"EXPORT-COMPATIBILITY.md",net.oceancanvas.mod.planning.OceanCanvasP5PipelineService.compatibilityMarkdown());
            write(zip,"WORLDPAINTER.md",net.oceancanvas.mod.planning.OceanCanvasP5PipelineService.worldPainterManifest(world,project));
            write(zip,"LITEMATICA.md",net.oceancanvas.mod.planning.OceanCanvasP5PipelineService.litematicaManifest(world,project.id()));
            write(zip,"pipeline/terrain-fingerprints.sha256",terrainFingerprints(terrain));
            write(zip,"README.md",humanReadme(project,tasks,planObjects,terrain));
            write(zip,"README.txt","Ocean Canvas portable project package\n\nSee README.md for the human-readable bundle index and pipeline contract.\nFormat: oceancanvas-project v4\nExported by "+OceanCanvas.VERSION+"\nProject id: "+project.id()+"\n");
        }
        return new Result(file,tasks.size(),planObjects.size(),terrain.size());
    }
    private static void write(ZipOutputStream zip,String name,String text)throws IOException{zip.putNextEntry(new ZipEntry(name));zip.write(text.getBytes(StandardCharsets.UTF_8));zip.closeEntry();}
    private static String json(OceanCanvasWorkspaceData.WorkProject p,java.util.List<OceanCanvasWorkspaceData.GeoTask> tasks,java.util.List<OceanCanvasPlanningData.PlanningObject> objects,java.util.List<OceanCanvasPlanLibraryData.TerrainAsset> assets,java.util.List<OceanCanvasPipelineSnapshotData.Entry> checkpoints){StringBuilder s=new StringBuilder();
        s.append("{\n  \"format\":\"oceancanvas-project\",\n  \"formatVersion\":4,\n  \"coordinateContract\":{\"version\":1,\"axes\":\"X_EAST_Z_SOUTH\",\"origin\":\"WORLD_0_0_OR_SAVED_TRANSFORM\",\"bounds\":\"MIN_MAX_INCLUSIVE\",\"seaLevel\":\"EXPLICIT\",\"fingerprint\":\"SHA-256\"},\n  \"oceanCanvasVersion\":\"").append(esc(OceanCanvas.VERSION)).append("\",\n");
        s.append("  \"project\":{").append("\"id\":\"").append(esc(p.id())).append("\",\"name\":\"").append(esc(p.name())).append("\",\"status\":\"").append(esc(p.status())).append("\",\"regionName\":\"").append(esc(p.regionName())).append("\",\"parentProjectId\":\"").append(esc(p.parentProjectId())).append("\",\"templateId\":\"").append(esc(p.templateId())).append("\",\"notes\":\"").append(esc(p.notes())).append("\",\"createdAt\":").append(p.createdAt()).append(",\"updatedAt\":").append(p.updatedAt()).append(",\"currentTaskId\":\"").append(esc(p.currentTaskId())).append("\",\"milestones\":[");
        strings(s,p.milestones());
        s.append("],\"phases\":[");int n=0;for(var ph:p.phases()){if(n++>0)s.append(',');s.append("{\"id\":\"").append(esc(ph.id())).append("\",\"name\":\"").append(esc(ph.name())).append("\",\"status\":\"").append(esc(ph.status())).append("\",\"order\":").append(ph.order()).append('}');}
        s.append("],\"blockers\":[");n=0;for(var b:p.blockers()){if(n++>0)s.append(',');s.append("{\"id\":\"").append(esc(b.id())).append("\",\"text\":\"").append(esc(b.text())).append("\",\"resolved\":").append(b.resolved()).append(",\"scopeType\":\"").append(esc(b.scopeType())).append("\",\"scopeId\":\"").append(esc(b.scopeId())).append("\"}");}
        s.append("],\"milestoneRecords\":[");n=0;for(var m:p.milestoneRecords()){if(n++>0)s.append(',');s.append("{\"id\":\"").append(esc(m.id())).append("\",\"name\":\"").append(esc(m.name())).append("\",\"status\":\"").append(esc(m.status())).append("\",\"phaseId\":\"").append(esc(m.phaseId())).append("\",\"taskId\":\"").append(esc(m.taskId())).append("\",\"notes\":\"").append(esc(m.notes())).append("\",\"progress\":").append(m.progress()).append(",\"targetDate\":\"").append(esc(m.targetDate())).append("\"}");}
        s.append("]},\n  \"tasks\":[");n=0;for(var t:tasks){if(n++>0)s.append(',');s.append("{\"id\":\"").append(esc(t.id())).append("\",\"title\":\"").append(esc(t.title())).append("\",\"notes\":\"").append(esc(t.notes())).append("\",\"x\":").append(t.x()).append(",\"z\":").append(t.z()).append(",\"status\":\"").append(esc(t.status())).append("\",\"priority\":").append(t.priority()).append(",\"weight\":").append(String.format(Locale.ROOT,"%.4f",t.weight())).append(",\"phaseId\":\"").append(esc(t.phaseId())).append("\",\"planningObjectId\":\"").append(esc(t.planningObjectId())).append("\",\"parentTaskId\":\"").append(esc(t.parentTaskId())).append("\",\"dependencies\":[");strings(s,t.dependencies());s.append("],\"checklist\":[");int c=0;for(var i:t.checklist()){if(c++>0)s.append(',');s.append("{\"id\":\"").append(esc(i.id())).append("\",\"text\":\"").append(esc(i.text())).append("\",\"complete\":").append(i.complete()).append('}');}s.append("]}");}s.append("],\n  \"planObjects\":[");
        n=0;for(var o:objects){if(n++>0)s.append(',');s.append("{\"id\":\"").append(esc(o.id())).append("\",\"type\":\"").append(esc(o.type())).append("\",\"name\":\"").append(esc(o.name())).append("\",\"points\":[");for(int i=0;i<o.points().size();i++){if(i>0)s.append(',');var q=o.points().get(i);s.append('[').append(q.x()).append(',').append(q.z()).append(']');}s.append("]}");}s.append("],\n  \"terrainAssets\":[");
        n=0;for(var a:assets){if(n++>0)s.append(',');s.append("{\"id\":\"").append(esc(a.id())).append("\",\"name\":\"").append(esc(a.name())).append("\",\"status\":\"").append(esc(a.status())).append("\",\"bounds\": [").append(a.minX()).append(',').append(a.minZ()).append(',').append(a.maxX()).append(',').append(a.maxZ()).append("],\"seaLevel\":").append(a.seaLevel()).append(",\"approvedGaeaRevision\":\"").append(esc(a.approvedGaeaRevision())).append("\",\"approvedWorldPainterRevision\":\"").append(esc(a.approvedWorldPainterRevision())).append("\",\"placementData\":\"").append(esc(a.placementData())).append("\",\"revisions\":[");int rr=0;for(var rev:a.revisions()){if(rr++>0)s.append(',');s.append("{\"id\":\"").append(esc(rev.id())).append("\",\"stage\":\"").append(esc(rev.stage())).append("\",\"fileName\":\"").append(esc(rev.fileName())).append("\",\"fileHash\":\"").append(esc(rev.fileHash())).append("\",\"bounds\":[").append(rev.minX()).append(',').append(rev.minZ()).append(',').append(rev.maxX()).append(',').append(rev.maxZ()).append("],\"widthPx\":").append(rev.widthPx()).append(",\"heightPx\":").append(rev.heightPx()).append(",\"blocksPerPixel\":").append(String.format(Locale.ROOT,"%.8f",rev.blocksPerPixel())).append(",\"seaLevel\":").append(rev.seaLevel()).append(",\"orientation\":\"").append(esc(rev.orientation())).append("\",\"createdAt\":").append(rev.createdAt()).append(",\"fingerprint\":\"").append(net.oceancanvas.mod.planning.OceanCanvasP5PipelineService.fingerprint(a,rev)).append("\"}");}s.append("]}");}
        s.append("],\n  \"pipelineCheckpoints\":[");n=0;for(var c:checkpoints){if(n++>0)s.append(',');s.append("{\"epochMillis\":").append(c.epochMillis()).append(",\"label\":\"").append(esc(c.label())).append("\",\"plans\":").append(c.plans()).append(",\"implemented\":").append(c.implemented()).append(",\"assets\":").append(c.assets()).append(",\"revisions\":").append(c.revisions()).append(",\"gaea\":").append(c.gaea()).append(",\"worldPainter\":").append(c.worldPainter()).append(",\"placement\":").append(c.placement()).append(",\"tasks\":").append(c.tasks()).append(",\"complete\":").append(c.complete()).append(",\"ready\":").append(c.ready()).append(",\"phasesComplete\":").append(c.phasesComplete()).append(",\"milestonesComplete\":").append(c.milestonesComplete()).append(",\"blockers\":").append(c.blockers()).append('}');}return s.append("]\n}\n").toString();}
    private static String terrainFingerprints(java.util.List<OceanCanvasPlanLibraryData.TerrainAsset> assets){StringBuilder s=new StringBuilder();for(var a:assets)for(var r:a.revisions())s.append(net.oceancanvas.mod.planning.OceanCanvasP5PipelineService.fingerprint(a,r)).append("  ").append(a.id()).append('/').append(r.id()).append("  ").append(r.fileName()).append('\n');return s.toString();}
    private static String humanReadme(OceanCanvasWorkspaceData.WorkProject p,java.util.List<OceanCanvasWorkspaceData.GeoTask> tasks,java.util.List<OceanCanvasPlanningData.PlanningObject> objects,java.util.List<OceanCanvasPlanLibraryData.TerrainAsset> assets){StringBuilder s=new StringBuilder("# Ocean Canvas Project Bundle\n\n");s.append("**Project:** ").append(p.name()).append(" (`").append(p.id()).append("`)  \n**Status:** ").append(p.status()).append("  \n**Region:** ").append(p.regionName().isBlank()?"—":p.regionName()).append("  \n**Ocean Canvas:** ").append(OceanCanvas.VERSION).append("\n\n");s.append("This v4 bundle is metadata-first and reproducible. It contains no chunks or player data and does not apply terrain when opened. External returns should enter Ocean Canvas through P5 quarantine, contract validation, fingerprint/drift checks, then explicit reconciliation.\n\n## Contents\n\n- `manifest.json` — versioned project/Plan/Terrain Asset lineage, including revision fingerprints.\n- `pipeline/coordinate-contract.txt` — exact X/Z/origin/bounds/sea-level contract.\n- `pipeline/transforms.json` — saved coordinate-transform profiles.\n- `pipeline/export-recipes.json` — reproducible export recipes.\n- `pipeline/terrain-fingerprints.sha256` — deterministic revision fingerprints.\n- `WORLDPAINTER.md` — layer and alignment handoff manifest.\n- `LITEMATICA.md` — placement registry manifest.\n- `EXPORT-COMPATIBILITY.md` — preserved/lost capabilities by target format.\n- `schema/oceancanvas-project-v4.schema.json` — interchange schema.\n- `ATLAS.md`, `atlas-index.json`, `atlas-map.svg` — human-readable project atlas.\n\n## Inventory\n\n- Tasks: ").append(tasks.size()).append("\n- Plan objects: ").append(objects.size()).append("\n- Terrain assets: ").append(assets.size()).append("\n\n## Safety\n\nImporting/previewing this bundle never mutates Minecraft terrain. Terrain changes continue to require Ocean Canvas' explicit operation/deployment path.\n");return s.toString();}
    private static void strings(StringBuilder s,java.util.List<String> values){for(int i=0;i<values.size();i++){if(i>0)s.append(',');s.append('"').append(esc(values.get(i))).append('"');}}
    private static String mission(OceanCanvasWorkspaceData.WorkProject p){for(String line:p.notes().split("\\R"))if(line.startsWith("Mission: "))return line.substring(9).split(" — ",2)[0].trim();return "";}
    private static boolean related(OceanCanvasWorkspaceData.WorkProject p,OceanCanvasAtlasRouteData.Stop stop){return switch(stop.kind()){case "MISSION"->stop.targetId().equals(p.id());case "MILESTONE"->stop.targetId().startsWith(p.id()+":");case "REGION"->!p.regionName().isBlank()&&stop.targetId().equalsIgnoreCase(p.regionName());default->false;};}
    private static java.util.List<OceanCanvasAtlasRouteData.Route> relatedRoutes(ServerLevel world,OceanCanvasWorkspaceData.WorkProject p){return OceanCanvasAtlasRouteData.get(world).routes().stream().filter(r->r.stops().stream().anyMatch(s->related(p,s))).toList();}
    private static String atlasJson(ServerLevel world,OceanCanvasWorkspaceData.WorkProject p){var zones=net.oceancanvas.mod.worldgen.OceanCanvasPlayerZones.get(world);var zone=p.regionName().isBlank()?null:zones.zoneByName(p.regionName());var routes=relatedRoutes(world,p);StringBuilder s=new StringBuilder("{\n  \"format\":\"oceancanvas-atlas-index\",\n  \"formatVersion\":1,\n  \"projectId\":\"").append(esc(p.id())).append("\",\n  \"projectName\":\"").append(esc(p.name())).append("\",\n  \"mission\":\"").append(esc(mission(p))).append("\",\n  \"region\":{");if(zone==null)s.append("\"name\":\"").append(esc(p.regionName())).append("\",\"available\":false");else s.append("\"name\":\"").append(esc(zone.name())).append("\",\"available\":true,\"bounds\": [").append(zone.bounds().minX()).append(',').append(zone.bounds().minZ()).append(',').append(zone.bounds().maxX()).append(',').append(zone.bounds().maxZ()).append(']');s.append("},\n  \"milestones\":[");int n=0;for(var m:p.milestoneRecords()){if(n++>0)s.append(',');s.append("{\"id\":\"").append(esc(m.id())).append("\",\"name\":\"").append(esc(m.name())).append("\",\"status\":\"").append(esc(m.status())).append("\",\"progress\":").append(m.progress()).append(",\"targetDate\":\"").append(esc(m.targetDate())).append("\"}");}s.append("],\n  \"routes\":[");n=0;for(var r:routes){if(n++>0)s.append(',');s.append("{\"id\":\"").append(esc(r.id())).append("\",\"name\":\"").append(esc(r.name())).append("\",\"stops\":[");int q=0;for(var stop:r.stops()){if(q++>0)s.append(',');s.append("{\"kind\":\"").append(esc(stop.kind())).append("\",\"targetId\":\"").append(esc(stop.targetId())).append("\",\"title\":\"").append(esc(stop.title())).append("\",\"x\":").append(stop.x()).append(",\"z\":").append(stop.z()).append(",\"order\":").append(stop.order()).append('}');}s.append("]}");}return s.append("]\n}\n").toString();}
    private static String atlasMarkdown(ServerLevel world,OceanCanvasWorkspaceData.WorkProject p){var zone=p.regionName().isBlank()?null:net.oceancanvas.mod.worldgen.OceanCanvasPlayerZones.get(world).zoneByName(p.regionName());StringBuilder s=new StringBuilder("# ").append(p.name()).append(" — World Atlas\n\n");String mission=mission(p);if(!mission.isBlank())s.append("Mission: **").append(mission).append("**\n\n");s.append("Project status: ").append(p.status()).append("\n\n");if(zone!=null)s.append("Region: ").append(zone.name()).append(" (`").append(zone.bounds().minX()).append(", ").append(zone.bounds().minZ()).append("` → `").append(zone.bounds().maxX()).append(", ").append(zone.bounds().maxZ()).append("`)\n\n");s.append("## Milestones\n\n");if(p.milestoneRecords().isEmpty())s.append("No structured milestones.\n");else for(var m:p.milestoneRecords())s.append("- ").append(m.name()).append(" — ").append(m.status()).append(" — ").append(m.progress()).append('%').append(m.targetDate().isBlank()?"":" — target "+m.targetDate()).append('\n');s.append("\n## Atlas journeys\n\n");var routes=relatedRoutes(world,p);if(routes.isEmpty())s.append("No Atlas route currently references this Project's Mission, milestones, or Region.\n");for(var r:routes){s.append("### ").append(r.name()).append("\n\n");for(var stop:r.stops())s.append(stop.order()+1).append(". ").append(stop.title()).append(" — ").append(stop.kind()).append(" — `").append(stop.x()).append(", ").append(stop.z()).append("`\n");s.append('\n');}return s.append("---\nThis Atlas companion is metadata only. It contains no terrain, chunks, screenshots, player data, or executable world changes.\n").toString();}
    private static String atlasJsonWithChapters(ServerLevel world,OceanCanvasWorkspaceData.WorkProject p){
        var zones=net.oceancanvas.mod.worldgen.OceanCanvasPlayerZones.get(world);var zone=p.regionName().isBlank()?null:zones.zoneByName(p.regionName());var routes=relatedRoutes(world,p);
        StringBuilder s=new StringBuilder("{\n  \"format\":\"oceancanvas-atlas-index\",\n  \"formatVersion\":2,\n  \"projectId\":\"").append(esc(p.id())).append("\",\n  \"projectName\":\"").append(esc(p.name())).append("\",\n  \"mission\":\"").append(esc(mission(p))).append("\",\n  \"region\":{");
        if(zone==null)s.append("\"name\":\"").append(esc(p.regionName())).append("\",\"available\":false");else s.append("\"name\":\"").append(esc(zone.name())).append("\",\"available\":true,\"bounds\": [").append(zone.bounds().minX()).append(',').append(zone.bounds().minZ()).append(',').append(zone.bounds().maxX()).append(',').append(zone.bounds().maxZ()).append(']');
        s.append("},\n  \"milestones\":[");int n=0;for(var m:p.milestoneRecords()){if(n++>0)s.append(',');s.append("{\"id\":\"").append(esc(m.id())).append("\",\"name\":\"").append(esc(m.name())).append("\",\"status\":\"").append(esc(m.status())).append("\",\"progress\":").append(m.progress()).append(",\"targetDate\":\"").append(esc(m.targetDate())).append("\"}");}
        s.append("],\n  \"routes\":[");n=0;for(var r:routes){if(n++>0)s.append(',');s.append("{\"id\":\"").append(esc(r.id())).append("\",\"name\":\"").append(esc(r.name())).append("\",\"description\":\"").append(esc(r.description())).append("\",\"stops\":[");int q=0;for(var stop:r.stops()){if(q++>0)s.append(',');s.append("{\"kind\":\"").append(esc(stop.kind())).append("\",\"targetId\":\"").append(esc(stop.targetId())).append("\",\"title\":\"").append(esc(stop.title())).append("\",\"x\":").append(stop.x()).append(",\"z\":").append(stop.z()).append(",\"order\":").append(stop.order()).append('}');}s.append("]}");}
        return s.append("]\n}\n").toString();
    }
    private static String atlasMarkdownWithChapters(ServerLevel world,OceanCanvasWorkspaceData.WorkProject p){
        var zone=p.regionName().isBlank()?null:net.oceancanvas.mod.worldgen.OceanCanvasPlayerZones.get(world).zoneByName(p.regionName());StringBuilder s=new StringBuilder("# ").append(p.name()).append(" — World Atlas\n\n");String mission=mission(p);if(!mission.isBlank())s.append("Mission: **").append(mission).append("**\n\n");s.append("Project status: ").append(p.status()).append("\n\n");if(zone!=null)s.append("Region: ").append(zone.name()).append(" (`").append(zone.bounds().minX()).append(", ").append(zone.bounds().minZ()).append("` → `").append(zone.bounds().maxX()).append(", ").append(zone.bounds().maxZ()).append("`)\n\n");s.append("## Milestones\n\n");if(p.milestoneRecords().isEmpty())s.append("No structured milestones.\n");else for(var m:p.milestoneRecords())s.append("- ").append(m.name()).append(" — ").append(m.status()).append(" — ").append(m.progress()).append('%').append(m.targetDate().isBlank()?"":" — target "+m.targetDate()).append('\n');s.append("\n## Atlas journeys\n\n");var routes=relatedRoutes(world,p);if(routes.isEmpty())s.append("No Atlas route currently references this Project's Mission, milestones, or Region.\n");for(var r:routes){s.append("### ").append(r.name()).append("\n\n");if(!r.description().isBlank())s.append(r.description()).append("\n\n");for(var stop:r.stops())s.append(stop.order()+1).append(". ").append(stop.title()).append(" — ").append(stop.kind()).append(" — `").append(stop.x()).append(", ").append(stop.z()).append("`\n");s.append('\n');}return s.append("---\nThis Atlas companion and its SVG map are metadata only. They contain no terrain, chunks, screenshots, player data, or executable world changes.\n").toString();
    }
    private static String atlasSvg(ServerLevel world,OceanCanvasWorkspaceData.WorkProject p){
        var zone=p.regionName().isBlank()?null:net.oceancanvas.mod.worldgen.OceanCanvasPlayerZones.get(world).zoneByName(p.regionName());var routes=relatedRoutes(world,p);
        long minX=Long.MAX_VALUE,minZ=Long.MAX_VALUE,maxX=Long.MIN_VALUE,maxZ=Long.MIN_VALUE;
        if(zone!=null){minX=zone.bounds().minX();minZ=zone.bounds().minZ();maxX=zone.bounds().maxX();maxZ=zone.bounds().maxZ();}
        for(var r:routes)for(var stop:r.stops()){minX=Math.min(minX,stop.x());minZ=Math.min(minZ,stop.z());maxX=Math.max(maxX,stop.x());maxZ=Math.max(maxZ,stop.z());}
        if(minX==Long.MAX_VALUE){minX=-512;minZ=-512;maxX=512;maxZ=512;}long pad=Math.max(32,Math.max(maxX-minX,maxZ-minZ)/12);minX-=pad;minZ-=pad;maxX+=pad;maxZ+=pad;
        String[] colors={"#67e8f9","#fbbf24","#f472b6","#a7f3d0","#c4b5fd","#fb7185"};StringBuilder s=new StringBuilder("<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 1200 800\" width=\"1200\" height=\"800\" role=\"img\" aria-label=\"Ocean Canvas Atlas map\">\n");
        s.append("<rect width=\"1200\" height=\"800\" fill=\"#071a26\"/><rect x=\"42\" y=\"92\" width=\"860\" height=\"650\" rx=\"18\" fill=\"#0b2d3c\" stroke=\"#38677a\" stroke-width=\"2\"/>");
        s.append("<text x=\"42\" y=\"48\" fill=\"#f8fafc\" font-family=\"sans-serif\" font-size=\"30\" font-weight=\"700\">").append(xml(p.name())).append(" — World Atlas</text><text x=\"42\" y=\"75\" fill=\"#9bd9e8\" font-family=\"sans-serif\" font-size=\"15\">Printable metadata map · X east/west · Z north/south</text>");
        if(zone!=null){double x=mapX(zone.bounds().minX(),minX,maxX),y=mapZ(zone.bounds().minZ(),minZ,maxZ),x2=mapX(zone.bounds().maxX(),minX,maxX),y2=mapZ(zone.bounds().maxZ(),minZ,maxZ);s.append("<rect x=\"").append(fmt(x)).append("\" y=\"").append(fmt(y)).append("\" width=\"").append(fmt(Math.max(1,x2-x))).append("\" height=\"").append(fmt(Math.max(1,y2-y))).append("\" fill=\"#155e75\" fill-opacity=\".28\" stroke=\"#22d3ee\" stroke-width=\"3\" stroke-dasharray=\"10 7\"/><text x=\"").append(fmt(x+10)).append("\" y=\"").append(fmt(y+22)).append("\" fill=\"#a5f3fc\" font-family=\"sans-serif\" font-size=\"16\">").append(xml(zone.name())).append("</text>");}
        int routeIndex=0;for(var r:routes){String color=colors[routeIndex%colors.length];if(r.stops().size()>1){s.append("<polyline points=\"");for(var stop:r.stops())s.append(fmt(mapX(stop.x(),minX,maxX))).append(',').append(fmt(mapZ(stop.z(),minZ,maxZ))).append(' ');s.append("\" fill=\"none\" stroke=\"").append(color).append("\" stroke-width=\"5\" stroke-linecap=\"round\" stroke-linejoin=\"round\" opacity=\".9\"/>");}int stopIndex=1;for(var stop:r.stops()){double x=mapX(stop.x(),minX,maxX),y=mapZ(stop.z(),minZ,maxZ);s.append("<circle cx=\"").append(fmt(x)).append("\" cy=\"").append(fmt(y)).append("\" r=\"12\" fill=\"").append(color).append("\" stroke=\"#071a26\" stroke-width=\"3\"/><text x=\"").append(fmt(x)).append("\" y=\"").append(fmt(y+5)).append("\" text-anchor=\"middle\" fill=\"#071a26\" font-family=\"sans-serif\" font-size=\"12\" font-weight=\"700\">").append(stopIndex++).append("</text><text x=\"").append(fmt(x+16)).append("\" y=\"").append(fmt(y-10)).append("\" fill=\"#f8fafc\" font-family=\"sans-serif\" font-size=\"13\">").append(xml(stop.title())).append("</text>");}double ly=128+routeIndex*76;s.append("<line x1=\"940\" y1=\"").append(fmt(ly)).append("\" x2=\"976\" y2=\"").append(fmt(ly)).append("\" stroke=\"").append(color).append("\" stroke-width=\"5\"/><text x=\"988\" y=\"").append(fmt(ly+5)).append("\" fill=\"#f8fafc\" font-family=\"sans-serif\" font-size=\"16\" font-weight=\"700\">").append(xml(r.name())).append("</text>");if(!r.description().isBlank()){String d=r.description().length()>52?r.description().substring(0,49)+"…":r.description();s.append("<text x=\"940\" y=\"").append(fmt(ly+25)).append("\" fill=\"#a8c9d4\" font-family=\"sans-serif\" font-size=\"12\">").append(xml(d)).append("</text>");}routeIndex++;}
        if(routes.isEmpty())s.append("<text x=\"472\" y=\"420\" text-anchor=\"middle\" fill=\"#a8c9d4\" font-family=\"sans-serif\" font-size=\"18\">No related Atlas journeys yet</text>");
        s.append("<text x=\"940\" y=\"710\" fill=\"#7899a5\" font-family=\"sans-serif\" font-size=\"12\">Generated from Region bounds and Atlas stop coordinates only.</text><text x=\"940\" y=\"730\" fill=\"#7899a5\" font-family=\"sans-serif\" font-size=\"12\">No chunks loaded · no terrain sampled</text></svg>\n");return s.toString();
    }
    private static double mapX(long x,long min,long max){return 62.0+(x-min)*820.0/Math.max(1.0,max-min);}
    private static double mapZ(long z,long min,long max){return 112.0+(z-min)*610.0/Math.max(1.0,max-min);}
    private static String fmt(double value){return String.format(Locale.ROOT,"%.1f",value);}
    private static String xml(String v){return v==null?"":v.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&apos;");}
    private static String safe(String v){String s=v==null?"project":v.trim().replaceAll("[^A-Za-z0-9._-]+","_").replaceAll("^_+|_+$","");return s.isBlank()?"project":s;}
    private static String esc(String v){return v==null?"":v.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r").replace("\t","\\t");}
}
