package net.oceancanvas.mod.project;

import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.ChunkPos;
import java.nio.file.*;
import java.util.*;

/** Runtime enforcement, upgrade/recovery preflight and health for Forever World metadata. */
public final class OceanCanvasForeverWorldStewardship {
    private OceanCanvasForeverWorldStewardship(){}
    public record Finding(String severity,String code,String detail){}
    public record Health(String state,String worldUuid,String role,int heritageEntries,int reserves,int frontiers,int rehearsals,int assets,List<Finding> findings){public boolean ready(){return "RECOVERY_READY".equals(state);}}

    public static String projectForRegion(ServerLevel world,String regionId){if(regionId==null||regionId.isBlank())return "";for(var p:OceanCanvasWorkspaceData.get(world).projects())if(p.regionName().equalsIgnoreCase(regionId))return p.id();return "";}

    public static String blockRect(ServerLevel world,String operation,int minChunkX,int maxChunkX,int minChunkZ,int maxChunkZ,String regionId,String projectId,String workAreaId){
        var data=OceanCanvasForeverWorldStewardshipData.get(world);
        observeRuntimeLocation(world);
        if(roleConfirmationRequired(data))return "Forever World blocked "+operation+": this save moved or was copied since its role was last confirmed. Run /oceancanvas forever role PRIMARY (or STAGING/BACKUP/EXPERIMENT/ARCHIVE as appropriate) before terrain mutation.";
        if(data.identity().role().equals("BACKUP")||data.identity().role().equals("ARCHIVE")){var roleOverride=OceanCanvasForeverWorldData.get(world).evaluateWorldPolicy("ROLE_MUTATION",regionId,projectId,workAreaId);if(roleOverride==null||!isAllow(roleOverride.value()))return "Forever World blocked "+operation+": world role "+data.identity().role()+" is read-only by default. Use a different role or an explicit scoped ROLE_MUTATION=ALLOW override.";}
        String op=operation==null?"MUTATE":operation.trim().toUpperCase(Locale.ROOT).replace('-','_');
        var reserve=data.reserveIntersecting(minChunkX,maxChunkX,minChunkZ,maxChunkZ);
        if(reserve!=null){var override=OceanCanvasForeverWorldData.get(world).evaluateWorldPolicy("RESERVE_MUTATION",regionId,projectId,workAreaId);boolean allow=override!=null&&isAllow(override.value());if(!allow)return "Forever World blocked "+operation+": intersects Future Generation Reserve '"+reserve.name()+"' ("+reserve.id()+"). Set an explicit scoped RESERVE_MUTATION=ALLOW policy only if you intentionally want to consume reserved future-generation land.";}
        var policies=OceanCanvasForeverWorldData.get(world);
        var global=policies.evaluateWorldPolicy("TERRAIN_MUTATION",regionId,projectId,workAreaId);if(global!=null&&isDeny(global.value()))return denied(operation,global);
        var specific=policies.evaluateWorldPolicy(op,regionId,projectId,workAreaId);if(specific==null)specific=policies.evaluateWorldPolicy("ALLOW_"+op,regionId,projectId,workAreaId);if(specific!=null&&isDeny(specific.value()))return denied(operation,specific);
        var freeze=policies.evaluateWorldPolicy("FREEZE_MUTATIONS",regionId,projectId,workAreaId);if(freeze!=null&&truthy(freeze.value()))return denied(operation,freeze);
        return "";
    }
    public static String blockChunks(ServerLevel world,String operation,Collection<Long> chunks,String regionId,String projectId,String workAreaId){if(chunks==null||chunks.isEmpty())return "";int minX=Integer.MAX_VALUE,maxX=Integer.MIN_VALUE,minZ=Integer.MAX_VALUE,maxZ=Integer.MIN_VALUE;for(long p:chunks){int x=ChunkPos.getX(p),z=ChunkPos.getZ(p);minX=Math.min(minX,x);maxX=Math.max(maxX,x);minZ=Math.min(minZ,z);maxZ=Math.max(maxZ,z);}String broad=blockRect(world,operation,minX,maxX,minZ,maxZ,regionId,projectId,workAreaId);if(!broad.isEmpty()&&!broad.contains("Future Generation Reserve"))return broad;for(var r:OceanCanvasForeverWorldStewardshipData.get(world).reserves())if(r.enabled())for(long p:chunks)if(r.contains(ChunkPos.getX(p),ChunkPos.getZ(p))){var override=OceanCanvasForeverWorldData.get(world).evaluateWorldPolicy("RESERVE_MUTATION",regionId,projectId,workAreaId);if(override==null||!isAllow(override.value()))return "Forever World blocked "+operation+": selected chunks intersect Future Generation Reserve '"+r.name()+"'.";}return broad.contains("Future Generation Reserve")?"":broad;}
    private static String denied(String operation,OceanCanvasWorldPolicyEvaluator.Decision d){return "Forever World blocked "+operation+" by policy "+d.key()+"="+d.value()+" from "+d.sourceLabel()+"."+(d.rationale().isBlank()?"":" "+d.rationale());}
    private static boolean isDeny(String v){String s=v==null?"":v.trim().toUpperCase(Locale.ROOT);return Set.of("DENY","BLOCK","FALSE","OFF","NEVER","NO").contains(s);}private static boolean isAllow(String v){String s=v==null?"":v.trim().toUpperCase(Locale.ROOT);return Set.of("ALLOW","TRUE","ON","YES").contains(s);}private static boolean truthy(String v){return isAllow(v);}

    private static String heritageType(String operation){String op=operation==null?"":operation.toUpperCase(Locale.ROOT);return op.contains("RESTORE")?"VANILLA_RESTORED":op.contains("REWIPE")||op.contains("RESET")?"CANVAS":op.contains("PREGEN")?"CANVAS_PREGEN":op.contains("EXPAND")?"CANVAS_EXPANSION":"MODIFIED";}
    public static void recordCompleted(ServerLevel world,String operation,int minX,int maxX,int minZ,int maxZ,String revisionRef){var d=OceanCanvasForeverWorldStewardshipData.get(world);d.recordHeritage(minX,maxX,minZ,maxZ,heritageType(operation),"minecraft-26.2",revisionRef,"Ocean Canvas "+operation);d.addLineage("OPERATION_COMPLETED","",operation+" completed over chunks ["+minX+","+minZ+"]..["+maxX+","+maxZ+"]");}
    /** Compress an arbitrary exact chunk mask into horizontal runs so Heritage never claims holes were touched. */
    public static void recordCompletedChunks(ServerLevel world,String operation,Collection<Long> chunks,String revisionRef){if(chunks==null||chunks.isEmpty())return;var rows=new TreeMap<Integer,TreeSet<Integer>>();for(long p:chunks)rows.computeIfAbsent(ChunkPos.getZ(p),k->new TreeSet<>()).add(ChunkPos.getX(p));var d=OceanCanvasForeverWorldStewardshipData.get(world);int runs=0;for(var e:rows.entrySet()){Integer start=null,last=null;for(int x:e.getValue()){if(start==null){start=last=x;continue;}if(x==last+1){last=x;continue;}d.recordHeritage(start,last,e.getKey(),e.getKey(),heritageType(operation),"minecraft-26.2",revisionRef,"Ocean Canvas "+operation);runs++;start=last=x;}if(start!=null){d.recordHeritage(start,last,e.getKey(),e.getKey(),heritageType(operation),"minecraft-26.2",revisionRef,"Ocean Canvas "+operation);runs++;}}d.addLineage("OPERATION_COMPLETED","",operation+" completed over "+chunks.size()+" exact chunk(s), compressed into "+runs+" Heritage span(s)");}
    /** Record an already-compressed exact chunk scope without expanding it back into boxed chunk keys. */
    public static void recordCompletedChunkRuns(ServerLevel world,String operation,Collection<net.oceancanvas.mod.worldgen.OceanCanvasPlayerZones.ChunkRunView> chunkRuns,String revisionRef){
        if(chunkRuns==null||chunkRuns.isEmpty())return;var d=OceanCanvasForeverWorldStewardshipData.get(world);long chunks=0;int runs=0;
        for(var r:chunkRuns){if(r==null||r.maxX()<r.minX())continue;d.recordHeritage(r.minX(),r.maxX(),r.z(),r.z(),heritageType(operation),"minecraft-26.2",revisionRef,"Ocean Canvas "+operation);chunks+=(long)r.maxX()-r.minX()+1L;runs++;}
        d.addLineage("OPERATION_COMPLETED","",operation+" completed over "+chunks+" exact chunk(s), already compressed into "+runs+" Heritage span(s)");
    }
    /** Record an expansion ring without falsely marking the excluded existing interior as newly generated. */
    public static void recordCompletedRing(ServerLevel world,String operation,int minX,int maxX,int minZ,int maxZ,int exMinX,int exMaxX,int exMinZ,int exMaxZ,String revisionRef){if(exMinX>exMaxX||exMinZ>exMaxZ){recordCompleted(world,operation,minX,maxX,minZ,maxZ,revisionRef);return;}var d=OceanCanvasForeverWorldStewardshipData.get(world);String t=heritageType(operation),src="Ocean Canvas "+operation;if(minZ<exMinZ)d.recordHeritage(minX,maxX,minZ,Math.min(maxZ,exMinZ-1),t,"minecraft-26.2",revisionRef,src);if(maxZ>exMaxZ)d.recordHeritage(minX,maxX,Math.max(minZ,exMaxZ+1),maxZ,t,"minecraft-26.2",revisionRef,src);int mz0=Math.max(minZ,exMinZ),mz1=Math.min(maxZ,exMaxZ);if(mz0<=mz1){if(minX<exMinX)d.recordHeritage(minX,Math.min(maxX,exMinX-1),mz0,mz1,t,"minecraft-26.2",revisionRef,src);if(maxX>exMaxX)d.recordHeritage(Math.max(minX,exMaxX+1),maxX,mz0,mz1,t,"minecraft-26.2",revisionRef,src);}d.addLineage("OPERATION_COMPLETED","",operation+" expansion ring completed without attributing the excluded interior");}

    public static boolean observeRuntimeLocation(ServerLevel world){String here=world.getServer().getWorldPath(net.minecraft.world.level.storage.LevelResource.ROOT).toAbsolutePath().normalize().toString();var d=OceanCanvasForeverWorldStewardshipData.get(world);String previous="";for(var e:d.lineage())if(e.eventType().equals("WORLD_LOCATION"))previous=e.detail();if(previous.equals(here))return false;if(!previous.isBlank())d.addLineage("WORLD_LOCATION_CHANGED","","Previous="+previous+" | Current="+here);d.addLineage("WORLD_LOCATION","",here);return !previous.isBlank();}

    private static boolean roleConfirmationRequired(OceanCanvasForeverWorldStewardshipData d){long changed=0,confirmed=0;for(var e:d.lineage()){if(e.eventType().equals("WORLD_LOCATION_CHANGED"))changed=Math.max(changed,e.happenedAt());if(e.eventType().equals("ROLE_CHANGED"))confirmed=Math.max(confirmed,e.happenedAt());}return changed>confirmed;}

    public static Health health(ServerLevel world){observeRuntimeLocation(world);var d=OceanCanvasForeverWorldStewardshipData.get(world);var f=new ArrayList<Finding>();if(roleConfirmationRequired(d))f.add(new Finding("ERROR","WORLD_COPY_OR_MOVE_UNCLASSIFIED","The save path changed after the last role confirmation. Classify this copy/move before destructive work."));var id=d.identity();if(id.worldUuid().isBlank())f.add(new Finding("ERROR","IDENTITY_MISSING","Stable World UUID is missing."));if(!id.role().equals("PRIMARY")&&id.parentWorldUuid().isBlank())f.add(new Finding("WARN","LINEAGE_PARENT_MISSING",id.role()+" world has no parent World UUID."));
        for(var r:d.reserves()){if(r.expectedVersion().isBlank())f.add(new Finding("WARN","RESERVE_VERSION_UNKNOWN","Reserve '"+r.name()+"' has no expected future version."));for(var h:d.heritage())if(r.enabled()&&overlaps(r.minChunkX(),r.maxChunkX(),r.minChunkZ(),r.maxChunkZ(),h.minChunkX(),h.maxChunkX(),h.minChunkZ(),h.maxChunkZ())&&!h.heritageType().equals("UNKNOWN"))f.add(new Finding("ERROR","RESERVE_ALREADY_TOUCHED","Reserve '"+r.name()+"' overlaps recorded heritage "+h.heritageType()+" from "+h.source()+"."));}
        for(var a:d.assets()){if(a.required()&&a.path().isBlank())f.add(new Finding("ERROR","ASSET_PATH_MISSING","Required asset '"+a.label()+"' has no path."));else if(a.required()&&!exists(world,a.path()))f.add(new Finding("ERROR","ASSET_MISSING","Required asset '"+a.label()+"' is unavailable at its recorded path."));if(!a.portable())f.add(new Finding("WARN","ASSET_NOT_PORTABLE","Asset '"+a.label()+"' is marked non-portable."));try{if(!a.path().isBlank()&&Path.of(a.path()).isAbsolute())f.add(new Finding("WARN","ASSET_ABSOLUTE_PATH","Asset '"+a.label()+"' uses an absolute path; package or remap it before moving the world."));}catch(Exception ignored){}}
        for(var fr:d.frontiers())if(fr.status().equals("OPEN")&&fr.targetVersion().isBlank())f.add(new Finding("ERROR","OPEN_FRONTIER_VERSION_UNKNOWN","Open frontier '"+fr.name()+"' has no target Minecraft version."));
        var assetHealth=OceanCanvasAssetIntegrityService.scan(world,64);if(!assetHealth.healthy())f.add(new Finding("ERROR","WORLD_MODEL_LINKS",assetHealth.issues()+" broken Plan/Project/Terrain Asset link(s)."));
        String state=f.stream().anyMatch(x->x.severity().equals("ERROR"))?"INCOMPLETE":f.isEmpty()?"RECOVERY_READY":"NEEDS_ATTENTION";return new Health(state,id.worldUuid(),id.role(),d.heritage().size(),d.reserves().size(),d.frontiers().size(),d.rehearsals().size(),d.assets().size(),List.copyOf(f));}
    private static boolean exists(ServerLevel world,String p){try{Path q=Path.of(p);if(!q.isAbsolute())q=world.getServer().getWorldPath(net.minecraft.world.level.storage.LevelResource.ROOT).resolve(q);return Files.exists(q.normalize());}catch(Exception e){return false;}}private static boolean overlaps(int a,int b,int c,int d,int e,int f,int g,int h){return a<=f&&b>=e&&c<=h&&d>=g;}

    public static String compatibilityReport(ServerLevel world,String targetVersion){var h=health(world);var sb=new StringBuilder("Compatibility Report for ").append(targetVersion).append(": Forever World ").append(h.state()).append("; role=").append(h.role()).append("; heritage=").append(h.heritageEntries()).append("; reserves=").append(h.reserves()).append("; frontiers=").append(h.frontiers()).append(". ");String persistence=OceanCanvasPersistenceCompatibility.destructiveOperationBlockReason(world);if(!persistence.isBlank())sb.append("Persistence blocker: ").append(persistence).append(' ');for(var x:h.findings())sb.append(x.severity()).append(' ').append(x.code()).append(": ").append(x.detail()).append(' ');return sb.toString().trim();}
    public static String rebuildRecoveryMetadata(ServerLevel world){var r=OceanCanvasDeepHealthService.repairMetadata(world);OceanCanvasMetadataSnapshotData.get(world).capture(world,"forever-world-recovery-rebuild","Rebuilt derived metadata during Forever World recovery drill");OceanCanvasForeverWorldStewardshipData.get(world).addLineage("RECOVERY_REBUILD","","Metadata repair: repaired="+r.repaired()+", skipped="+r.skipped()+". "+r.detail());return "Recovery rebuild completed: "+r.repaired()+" repaired, "+r.skipped()+" skipped. "+r.detail();}

    public static String upgradeGate(ServerLevel world,String targetVersion){var d=OceanCanvasForeverWorldStewardshipData.get(world);var policy=OceanCanvasForeverWorldData.get(world).evaluateWorldPolicy("REQUIRE_UPGRADE_REHEARSAL","","","");boolean required=policy!=null&&truthy(policy.value());if(required&&!d.hasValidatedRehearsalFor(targetVersion))return "Upgrade blocked: REQUIRE_UPGRADE_REHEARSAL is enabled and no VALIDATED rehearsal targets Minecraft "+targetVersion+".";return "";}
}
