package net.oceancanvas.mod.command;

import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.arguments.StringArgumentType;
import me.lucko.fabric.api.permissions.v0.Permissions;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;
import net.minecraft.network.chat.Component;
import net.oceancanvas.mod.diagnostic.OceanCanvasHarnessCore;
import net.oceancanvas.mod.project.OceanCanvasHarnessService;
import net.oceancanvas.mod.diagnostic.OceanCanvasPerformanceReplayRecorder;

/** Explicit developer/support entry points for the shared ARCH-15 harness. */
public final class HarnessCommand {
    private HarnessCommand(){}
    public static void register(CommandDispatcher<CommandSourceStack> dispatcher){
        dispatcher.register(Commands.literal("oceancanvas").then(Commands.literal("harness")
                .requires(Permissions.require("oceancanvas.protect",2))
                .executes(c->status(c.getSource()))
                .then(Commands.literal("status").executes(c->status(c.getSource())))
                .then(Commands.literal("benchmark").executes(c->benchmark(c.getSource())))
                .then(Commands.literal("boundary").executes(c->boundary(c.getSource())))
                .then(Commands.literal("simulate").executes(c->simulate(c.getSource())))
                .then(Commands.literal("migration").executes(c->migration(c.getSource())))
                .then(Commands.literal("rehearsal-clone").executes(c->cloneHelp(c.getSource()))
                        .then(Commands.literal("confirm").executes(c->cloneWorld(c.getSource()))))
                .then(Commands.literal("replay").executes(c->replay(c.getSource())))
                .then(Commands.literal("fixtures").executes(c->fixtures(c.getSource())))
                .then(Commands.literal("invariants").executes(c->invariants(c.getSource())))
                .then(Commands.literal("torture").executes(c->torture(c.getSource())))
                .then(Commands.literal("crash").executes(c->crash(c.getSource())))
                .then(Commands.literal("compatibility").executes(c->compatibility(c.getSource())))
                .then(Commands.literal("benchmark-runtime").executes(c->benchmarkRuntime(c.getSource())))
                .then(Commands.literal("schema-fixtures").executes(c->schemaFixtures(c.getSource())))
                .then(Commands.literal("rehearsal-validate").executes(c->rehearsalValidate(c.getSource())))
                .then(Commands.literal("golden-pack").executes(c->goldenPack(c.getSource())))
                .then(Commands.literal("golden-status").executes(c->goldenStatus(c.getSource())))
                .then(Commands.literal("golden-evidence")
                        .then(Commands.argument("fixture",StringArgumentType.word())
                                .then(Commands.argument("verdict",StringArgumentType.word())
                                        .executes(c->goldenEvidence(c.getSource(),StringArgumentType.getString(c,"fixture"),StringArgumentType.getString(c,"verdict"),""))
                                        .then(Commands.argument("notes",StringArgumentType.greedyString()).executes(c->goldenEvidence(c.getSource(),StringArgumentType.getString(c,"fixture"),StringArgumentType.getString(c,"verdict"),StringArgumentType.getString(c,"notes")))))))
                .then(Commands.literal("decision-replay").executes(c->decisionReplay(c.getSource())))
                .then(Commands.literal("torture-runtime")
                        .then(Commands.literal("arm").executes(c->tortureRuntimeArm(c.getSource())))
                        .then(Commands.literal("verify").executes(c->tortureRuntimeVerify(c.getSource()))))
                .then(Commands.literal("crash-filesystem").executes(c->crashFilesystem(c.getSource())))
                .then(Commands.literal("p0").executes(c->p0(c.getSource())))
                .then(Commands.literal("all").executes(c->all(c.getSource())))));
    }
    private static int status(CommandSourceStack s){var checks=OceanCanvasHarnessService.regressionResults(s.getLevel());long fail=checks.stream().filter(v->v.verdict()==OceanCanvasHarnessService.Verdict.FAIL).count(),notRun=checks.stream().filter(v->v.verdict()==OceanCanvasHarnessService.Verdict.NOT_RUN).count();ok(s,"Reliability watchlist: "+(checks.size()-fail-notRun)+" checked, "+fail+" failed, "+notRun+" require runtime certification.");for(var c:checks)ok(s," - "+c.verdict()+" "+c.id()+": "+c.evidence());return fail==0?1:0;}
    private static int benchmark(CommandSourceStack s){try{String text=OceanCanvasHarnessService.benchmarkText(5000);var p=OceanCanvasHarnessService.writeReport(s.getLevel(),"benchmark",text);ok(s,text.trim()+"\nWritten to "+p);return 1;}catch(Exception e){return fail(s,"OC-HARNESS-BENCH: "+e.getMessage());}}
    private static int boundary(CommandSourceStack s){try{String text=OceanCanvasHarnessService.boundaryText(5000);var p=OceanCanvasHarnessService.writeReport(s.getLevel(),"boundary-fuzz",text);ok(s,text.trim()+"\nWritten to "+p);return text.contains("passed=true")?1:0;}catch(Exception e){return fail(s,"OC-HARNESS-BOUNDARY: "+e.getMessage());}}
    private static int simulate(CommandSourceStack s){try{String text=OceanCanvasHarnessService.simulatorText(512);var p=OceanCanvasHarnessService.writeReport(s.getLevel(),"synthetic-load",text);ok(s,"Synthetic load/fault matrix completed; report written to "+p);return text.contains("passed=false")?0:1;}catch(Exception e){return fail(s,"OC-HARNESS-SIM: "+e.getMessage());}}
    private static int migration(CommandSourceStack s){try{var p=OceanCanvasHarnessService.createMetadataRehearsalPack(s.getLevel());ok(s,"Created metadata-only migration rehearsal pack at "+p+". It is intentionally not a world backup or Minecraft-version clone.");return 1;}catch(Exception e){return fail(s,"OC-HARNESS-MIGRATION: "+e.getMessage());}}
    private static int replay(CommandSourceStack s){try{var samples=OceanCanvasPerformanceReplayRecorder.snapshot();var v=OceanCanvasPerformanceReplayRecorder.validate();var deterministic=OceanCanvasHarnessCore.replayDeterministically(samples);var p=OceanCanvasPerformanceReplayRecorder.export(s.getLevel());var exact=net.oceancanvas.mod.diagnostic.OceanCanvasOperationDecisionRecorder.validate();String exactText=exact.events()==0?"NOT_RUN":exact.passed()?"PASS":"FAIL";ok(s,"Performance replay exported to "+p+"; samples="+v.samples()+" invariantValid="+v.passed()+" deterministicValid="+deterministic.passed()+" transitions="+deterministic.transitions()+" checksum="+deterministic.checksum()+"; exactDecisionReplay="+exactText+" events="+exact.events()+".");return samples.isEmpty()?0:(v.passed()&&deterministic.passed()&&(exact.events()==0||exact.passed())?1:0);}catch(Exception e){return fail(s,"OC-HARNESS-REPLAY: "+e.getMessage());}}
    private static int fixtures(CommandSourceStack s){try{String text=OceanCanvasHarnessService.fixtureReport();var p=OceanCanvasHarnessService.writeReport(s.getLevel(),"golden-fixtures",text);ok(s,"Golden fixture manifest verified:\n"+text.trim()+"\nWritten to "+p);return 1;}catch(Exception e){return fail(s,"OC-HARNESS-FIXTURES: "+e.getMessage());}}
    private static int cloneHelp(CommandSourceStack s){ok(s,"World rehearsal cloning copies the entire saved world after a synchronous save and can pause the game while files are copied. It creates a sibling oceancanvas_rehearsals folder and NEVER alters the authoritative world. Run /oceancanvas harness rehearsal-clone confirm to proceed.");return 0;}
    private static int cloneWorld(CommandSourceStack s){try{var p=OceanCanvasHarnessService.createWorldRehearsalClone(s.getLevel());ok(s,"Created full migration rehearsal clone at "+p+". Test the COPY with the target Minecraft/Fabric/Ocean Canvas build; this does not certify the authoritative world.");return 1;}catch(Exception e){return fail(s,"OC-HARNESS-CLONE: "+e.getMessage());}}
    private static int invariants(CommandSourceStack s){try{String text=OceanCanvasHarnessService.invariantSuiteText();var p=OceanCanvasHarnessService.writeReport(s.getLevel(),"generated-invariants",text);ok(s,"Generated "+OceanCanvasHarnessCore.generatedInvariantSuite().size()+" invariant contracts at "+p+".");return 1;}catch(Exception e){return fail(s,"OC-HARNESS-INVARIANTS: "+e.getMessage());}}
    private static int torture(CommandSourceStack s){try{var r=OceanCanvasHarnessCore.runSaveQuitTorture();String text=OceanCanvasHarnessService.saveQuitTortureText();var p=OceanCanvasHarnessService.writeReport(s.getLevel(),"save-quit-torture",text);net.oceancanvas.mod.diagnostic.OceanCanvasHarnessData.get(s.getLevel()).record("OC-F227","SAVE_QUIT_TORTURE",r.passed()?"PASS":"FAIL",r.checksum(),r.cases(),"",text);ok(s,"Save/Quit interruption matrix: "+r.cases()+" cases, passed="+r.passed()+", report="+p+". Real client quit/reload remains a runtime golden fixture.");return r.passed()?1:0;}catch(Exception e){return fail(s,"OC-HARNESS-TORTURE: "+e.getMessage());}}
    private static int crash(CommandSourceStack s){try{var r=OceanCanvasHarnessCore.runCrashConsistencyMatrix();String text=OceanCanvasHarnessService.crashConsistencyText();var p=OceanCanvasHarnessService.writeReport(s.getLevel(),"crash-consistency",text);net.oceancanvas.mod.diagnostic.OceanCanvasHarnessData.get(s.getLevel()).record("OC-F232","CRASH_CONSISTENCY",r.passed()?"PASS":"FAIL",r.checksum(),r.cases(),"",text);ok(s,"Crash consistency matrix: "+r.cases()+" interruption points, passed="+r.passed()+", report="+p+".");return r.passed()?1:0;}catch(Exception e){return fail(s,"OC-HARNESS-CRASH: "+e.getMessage());}}
    private static int compatibility(CommandSourceStack s){try{var run=OceanCanvasHarnessService.recordCompatibility(s.getLevel());var p=OceanCanvasHarnessService.writeReport(s.getLevel(),"upgrade-compatibility",run.evidence());ok(s,"Upgrade compatibility fingerprint recorded: "+run.signature()+" verdict="+run.verdict()+" report="+p+".");return "PASS".equals(run.verdict())?1:0;}catch(Exception e){return fail(s,"OC-HARNESS-COMPAT: "+e.getMessage());}}
    private static int benchmarkRuntime(CommandSourceStack s){try{String text=net.oceancanvas.mod.project.OceanCanvasP0RuntimeHarness.runtimeBenchmarkText(s.getLevel(),5000);var p=OceanCanvasHarnessService.writeReport(s.getLevel(),"runtime-benchmark",text);ok(s,text.trim()+"\nWritten to "+p);return 1;}catch(Exception e){return fail(s,"OC-HARNESS-RUNTIME-BENCH: "+e.getMessage());}}
    private static int schemaFixtures(CommandSourceStack s){try{String text=net.oceancanvas.mod.project.OceanCanvasP0RuntimeHarness.historicalSchemaFixtureText();var p=OceanCanvasHarnessService.writeReport(s.getLevel(),"schema-fixtures",text);boolean pass=text.contains("failures=0 verdict=PASS");net.oceancanvas.mod.diagnostic.OceanCanvasHarnessData.get(s.getLevel()).record("OC-F229","HISTORICAL_SCHEMA_FIXTURES",pass?"PASS":"FAIL",0L,Double.NaN,"",text);ok(s,"Historical schema fixture matrix "+(pass?"PASS":"FAIL")+"; report="+p);return pass?1:0;}catch(Exception e){return fail(s,"OC-HARNESS-SCHEMA: "+e.getMessage());}}
    private static int rehearsalValidate(CommandSourceStack s){try{String text=net.oceancanvas.mod.project.OceanCanvasP0RuntimeHarness.validateRehearsalClone(s.getLevel());var p=OceanCanvasHarnessService.writeReport(s.getLevel(),"rehearsal-validation",text);ok(s,text.trim()+"\nWritten to "+p);return text.contains("verdict=PASS")?1:0;}catch(Exception e){return fail(s,"OC-HARNESS-REHEARSAL-VALIDATE: "+e.getMessage());}}
    private static int goldenPack(CommandSourceStack s){try{var p=net.oceancanvas.mod.project.OceanCanvasP0RuntimeHarness.prepareGoldenFixturePack(s.getLevel());ok(s,"Prepared reproducible golden-world fixture pack at "+p+". Run it only in a disposable rehearsal clone.");return 1;}catch(Exception e){return fail(s,"OC-HARNESS-GOLDEN-PACK: "+e.getMessage());}}
    private static int goldenStatus(CommandSourceStack s){try{ok(s,net.oceancanvas.mod.project.OceanCanvasP0RuntimeHarness.goldenEvidenceText(s.getLevel()).trim());return 1;}catch(Exception e){return fail(s,"OC-HARNESS-GOLDEN-STATUS: "+e.getMessage());}}
    private static int goldenEvidence(CommandSourceStack s,String fixture,String verdict,String notes){try{boolean pass=verdict.equalsIgnoreCase("pass")||verdict.equalsIgnoreCase("passed")||verdict.equalsIgnoreCase("true");if(!pass&&!verdict.equalsIgnoreCase("fail")&&!verdict.equalsIgnoreCase("failed")&&!verdict.equalsIgnoreCase("false"))return fail(s,"Verdict must be pass or fail.");ok(s,net.oceancanvas.mod.project.OceanCanvasP0RuntimeHarness.recordGoldenEvidence(s.getLevel(),fixture,pass,notes));return pass?1:0;}catch(Exception e){return fail(s,"OC-HARNESS-GOLDEN-EVIDENCE: "+e.getMessage());}}
    private static int decisionReplay(CommandSourceStack s){try{var r=net.oceancanvas.mod.diagnostic.OceanCanvasOperationDecisionRecorder.validate();if(r.events()==0){ok(s,"Exact operation decision replay has no events yet. Run a Pregen/Rewipe operation first; no fake PASS recorded.");return 0;}var p=net.oceancanvas.mod.diagnostic.OceanCanvasOperationDecisionRecorder.export(s.getLevel());net.oceancanvas.mod.diagnostic.OceanCanvasHarnessData.get(s.getLevel()).record("OC-F223","EXACT_DECISION_REPLAY",r.passed()?"PASS":"FAIL",r.checksum(),r.events(),"",p.toString());ok(s,"Exact decision replay: events="+r.events()+" admissions="+r.admissions()+" retirements="+r.retirements()+" live="+r.liveTargets()+" passed="+r.passed()+" report="+p);return r.passed()?1:0;}catch(Exception e){return fail(s,"OC-HARNESS-DECISION-REPLAY: "+e.getMessage());}}
    private static int tortureRuntimeArm(CommandSourceStack s){try{ok(s,net.oceancanvas.mod.project.OceanCanvasP0RuntimeHarness.armSaveQuitRuntime(s.getLevel()));return 1;}catch(Exception e){return fail(s,"OC-HARNESS-TORTURE-RUNTIME-ARM: "+e.getMessage());}}
    private static int tortureRuntimeVerify(CommandSourceStack s){try{String text=net.oceancanvas.mod.project.OceanCanvasP0RuntimeHarness.verifySaveQuitRuntime(s.getLevel());ok(s,text);return text.startsWith("PASS:")?1:0;}catch(Exception e){return fail(s,"OC-HARNESS-TORTURE-RUNTIME-VERIFY: "+e.getMessage());}}
    private static int crashFilesystem(CommandSourceStack s){try{String text=net.oceancanvas.mod.project.OceanCanvasP0RuntimeHarness.filesystemCrashConsistencyProbe(s.getLevel());ok(s,text.trim());return text.contains("verdict=PASS")?1:0;}catch(Exception e){return fail(s,"OC-HARNESS-CRASH-FS: "+e.getMessage());}}
    private static int p0(CommandSourceStack s){try{ok(s,net.oceancanvas.mod.project.OceanCanvasP0RuntimeHarness.p0Status(s.getLevel()));return 1;}catch(Exception e){return fail(s,"OC-HARNESS-P0: "+e.getMessage());}}
    private static int all(CommandSourceStack s){try{var boundary=OceanCanvasHarnessCore.runBoundaryFuzz(OceanCanvasHarnessCore.DEFAULT_SEED,5000);var replay=OceanCanvasPerformanceReplayRecorder.validate();var deterministic=OceanCanvasHarnessCore.replayDeterministically(OceanCanvasPerformanceReplayRecorder.snapshot());var torture=OceanCanvasHarnessCore.runSaveQuitTorture();var crash=OceanCanvasHarnessCore.runCrashConsistencyMatrix();String text=OceanCanvasHarnessService.report(s.getLevel())+"\n"+OceanCanvasHarnessService.benchmarkText(5000)+"\n"+OceanCanvasHarnessService.boundaryText(5000)+"\n"+OceanCanvasHarnessService.simulatorText(512)+"\nReplay invariantValid="+replay.passed()+" deterministicValid="+deterministic.passed()+" samples="+replay.samples()+"\n";var p=OceanCanvasHarnessService.writeReport(s.getLevel(),"full-harness",text);boolean pass=!OceanCanvasHarnessService.hasFailure(s.getLevel())&&boundary.passed()&&torture.passed()&&crash.passed()&&(replay.samples()==0||(replay.passed()&&deterministic.passed()));net.oceancanvas.mod.diagnostic.OceanCanvasHarnessData.get(s.getLevel()).record("OC-F248","FULL_HARNESS",pass?"PASS":"FAIL",boundary.checksum()^torture.checksum()^crash.checksum(),Double.NaN,"",p.toString());ok(s,"Full reliability report written to "+p+"; boundary="+boundary.passed()+", torture="+torture.passed()+", crash="+crash.passed()+", replay="+(replay.samples()==0?"NOT_RUN":(replay.passed()&&deterministic.passed()?"PASS":"FAIL"))+".");return pass?1:0;}catch(Exception e){return fail(s,"OC-HARNESS-ALL: "+e.getMessage());}}
    private static void ok(CommandSourceStack s,String text){s.sendSuccess(()->Component.literal(text),false);}private static int fail(CommandSourceStack s,String text){s.sendFailure(Component.literal(text));return 0;}
}
